Repository webdoky/content, pull requests merged in 2021-11, with the labels that each got.

#96 fix: fix indentation in js index page
  files/uk/web/javascript/index.md
Labels: bug

#83 /web/javascript/reference/global_objects/array/splice/index.md
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
Labels: translation

#85 translation: Web/JavaScript/Reference/Global_Objects/Array/Reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: translation

#86 translation: /docs/Web/JavaScript/Reference/Global_Objects/Array/sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: translation

#87 translation: /docs/Web/JavaScript/Reference/Global_Objects/Map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: translation

#88 translation: /docs/Web/JavaScript/Reference/Operators
  files/uk/web/javascript/reference/operators/index.md
Labels: translation

#89 translate: /docs/Web/JavaScript/Guide/Regular_Expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
  uk_spelling_additions.txt
Labels: translation

#102 fix: address the issues found by lt that happened while it wasn't working
  files/uk/web/css/--_star_/index.md
  files/uk/web/css/-moz-context-properties/index.md
  files/uk/web/css/-moz-force-broken-image-icon/index.md
  files/uk/web/css/specificity/index.md
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
  files/uk/web/javascript/reference/global_objects/date/index.md
  files/uk/web/javascript/reference/global_objects/map/index.md
  files/uk/web/javascript/reference/global_objects/promise/index.md
  files/uk/web/javascript/reference/operators/index.md
  uk_spelling_additions.txt
Labels: bug, translation

#104 translation: bring the outdated JS pages up to date
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
  files/uk/web/javascript/reference/global_objects/array/find/index.md
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
  files/uk/web/javascript/reference/global_objects/array/index.md
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: content

#111 chore: port web/index file from html to md
  files/uk/web/index.html
  files/uk/web/index.md
Labels: content

#113 fix: check-file.js, strip regex
  files/uk/web/css/specificity/index.md
  scripts/utils/check-file.js
  uk_spelling_additions.txt
Labels: bug

#94 translation: /docs/Web/JavaScript/Reference/Global_Objects/Array/includes
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
  uk_spelling_additions.txt
Labels: translation

#93 translation: /docs/Web/JavaScript/Reference/Global_Objects/String
  files/uk/web/javascript/reference/global_objects/string/index.md
  uk_spelling_additions.txt
Labels: translation

#98 translation: /Web/JavaScript/Reference/Operators/Conditional_Operator
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: translation

#99 translation: /docs/Web/JavaScript/Reference/Global_Objects/Object/entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: translation

#100 translation: /docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
  uk_spelling_additions.txt
Labels: translation

#105 translation(CSS): files/uk/web/css/display/index.md
  files/uk/web/css/display/index.md
  uk_ignore_additions.txt
Labels: translation
