Repository webdoky/content, pull requests merged in 2021-10, with the labels that each got.

#67 Refactoring & linting of code
  .editorconfig
  .eslintignore
  .eslintrc.cjs
  .prettierrc.cjs
  .vscode/settings.json
  Dockerfile
  disabled_rules.txt
  files/uk/web/javascript/reference/index.md
  package.json
  scripts/check-all.js
  scripts/check.js
  scripts/utils/check-file.js
  scripts/utils/countdown.js
  scripts/utils/debug.js
  scripts/utils/disabled-rules.js
  scripts/utils/execute.js
  scripts/utils/language-tool.js
  scripts/utils/print-correction.js
  scripts/utils/retry-until-timeout.js
  scripts/utils/sequential-async-map.js
  uk_spelling_additions.txt
  yarn.lock
Labels: enhancement

#22 translate reference page for Array.map()
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: translation

#19 translate web-js-ref-global_objects-array-filter page
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: translation

#71 Translation of web/css/--_star_/index.md
  files/uk/web/css/--_star_/index.md
Labels: translation

#72 translate javascript/reference/global_objects/date/index.md
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation

#73 Translation of web/css/-moz-context-properties/index.md
  files/uk/web/css/-moz-context-properties/index.md
  files/uk/web/css/index.md
Labels: translation

#76 web/css/-moz-float-edge/index.md
  files/uk/web/css/-moz-float-edge/index.md
  scripts/utils/check-file.js
Labels: translation

#77 web/css/-moz-force-broken-image-icon/index.md
  files/uk/web/css/-moz-force-broken-image-icon/index.md
Labels: translation

#80 Fixed typos & ran check
  files/uk/web/javascript/guide/index.md
  uk_spelling_additions.txt
Labels: content

#91 web/css/specificity/index.md
  files/uk/web/css/specificity/index.md
Labels: translation
