Repository webdoky/content, pull requests merged in 2022-06, with the labels that each got.

#314 Update/js
  files/uk/web/javascript/index.md
Labels: translation, update

#315 update(HTML): web/html/index.md
  files/uk/web/html/index.md
Labels: translation, update

#316 update(JS): web/javascript/reference/global_objects/array/filter/index.md
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: translation, update

#317 update(JS): web/javascript/reference/global_objects/array/map/index.md
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: translation, update

#318 update(JS): web/javascript/reference/global_objects/array/foreach/index.md
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: translation, update

#321 Update/js ref
  files/uk/web/javascript/reference/index.md
Labels: translation, update

#323 update(JS): web/javascript/reference/global_objects/array/find/index.md
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: translation, update

#286 update(css): /Web/CSS/display
  files/uk/web/css/display/index.md
Labels: content

#326 chore: added markdownlint config
  .markdownlint.json
Labels: enhancement

#325 update(JS): web/javascript/reference/global_objects/promise/index.md
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: update

#327 update(JS): web/javascript/reference/global_objects/date/index.md
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, update

#324 update(JS): web/javascript/reference/global_objects/array/splice/index.md
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
Labels: update

#330 update(JS): web/javascript/guide/regular_expressions/index.md
  files/uk/web/javascript/guide/regular_expressions/index.md
  uk_spelling_additions.txt
Labels: translation, update

#329 update(JS): web/javascript/reference/global_objects/array/slice/index.md
  files/uk/web/javascript/reference/global_objects/array/slice/index.md
Labels: translation, update

#328 update(JS): web/javascript/reference/global_objects/map/index.md
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: update

#320 update(HTML): web/html/element/input/index.md
  files/uk/web/html/element/input/index.md
Labels: translation, update

#335 update(JS): web/javascript/reference/global_objects/array/sort/index.md
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: translation, update

#331 translation(JS): /docs/Web/JavaScript/Reference/Operators/Spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: translation

#334 translation(JS): web/html/element/select/index.md
  files/uk/web/html/element/select/index.md
  uk_spelling_additions.txt
Labels: translation

#280 translation(js): /Web/JavaScript/Reference/Template_literals
  files/uk/web/javascript/reference/template_literals/index.md
  uk_spelling_additions.txt
Labels: translation

#288 update(css): /Web/CSS/Media_Queries/Using_media_queries
  files/uk/web/css/media_queries/using_media_queries/index.md
Labels: translation, update

#289 update(css): /Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox
  files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
Labels: translation, update

#291 update(css): /Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container
  files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
Labels: translation, update

#292 update(CSS): /docs/Web/CSS/cursor
  files/uk/web/css/cursor/index.md
Labels: translation, update

#293 update(CSS): /docs/Web/CSS/font-size
  files/uk/web/css/font-size/index.md
Labels: translation, update

#332 translation(JS): /docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
  files/uk/web/javascript/reference/operators/destructuring_assignment/index.md
Labels: translation

#279 translation(JS): /Web/JavaScript/Reference/Global_Objects/Object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: translation

#282 translation(js): /Web/JavaScript/Reference/Statements/async_function
  files/uk/web/javascript/reference/statements/async_function/index.md
Labels: translation

#283 translation(js): /Web/JavaScript/Reference/Operators/typeof
  files/uk/web/javascript/reference/operators/typeof/index.md
Labels: translation

#285 update(css): /Web/CSS/box-shadow
  files/uk/web/css/box-shadow/index.md
Labels: translation, update

#287 update(css): /Web/CSS/Using_CSS_custom_properties
  files/uk/web/css/using_css_custom_properties/index.md
Labels: translation, update

#336 update(css): /Web/CSS/Specificity
  files/uk/web/css/specificity/index.md
Labels: translation, update

#338 update(JS): web/javascript/reference/global_objects/string/index.md
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: update

#339 update(JS): web/javascript/reference/operators/index.md
  files/uk/web/javascript/reference/operators/index.md
Labels: update

#340 translation(HTML): web/html/element/div/index.md
  files/uk/web/html/element/div/index.md
Labels: translation

#342 chore: fix some anchors in /JavaScript/Reference/Global_Objects/Array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#341 chore: fix anchors in /docs/Web/JavaScript/Reference/Template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: update

#344 update(JS): web/javascript/reference/global_objects/date/index.md
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, update

#345 update(JS): web/javascript/reference/global_objects/array/includes/index.md
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
Labels: update

#333 translation(JS): /docs/Web/JavaScript/Reference/Global_Objects/Object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
  uk_spelling_additions.txt
Labels: translation

#346 Update/js ref go object entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: update

#348 update(JS): web/javascript/reference/global_objects/json/stringify/index.md
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: translation, update

#347 update(JS): web/javascript/reference/operators/conditional_operator/index.md
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: update

#349 update(CSS): web/css/position/index.md
  files/uk/web/css/position/index.md
Labels: update

#281 translation(js): /Web/JavaScript/Reference/Statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
  uk_spelling_additions.txt
Labels: translation

#350 translation(HTML): web/html/global_attributes/class/index.md
  files/uk/web/html/global_attributes/class/index.md
Labels: translation

#352 update(JS): web/javascript/index.md
  files/uk/web/javascript/index.md
  uk_spelling_additions.txt
Labels: update

#355 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#356 Update/html element input
  files/uk/web/html/element/input/index.md
Labels: update

#357 Update/js ref go string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update

#358 Update/js ref go json stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
  uk_spelling_additions.txt
Labels: translation, update

#359 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: translation, update

#360 update(JS): web/javascript/reference/global_objects/object/keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
  uk_spelling_additions.txt
Labels: update

#354 update(CSS): web/css/specificity/index.md
  files/uk/web/css/specificity/index.md
  uk_spelling_additions.txt
Labels: translation

#364 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: translation, update

#365 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: update

#361 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#399 translation(JS): /Web/JavaScript/Reference/Statements/for...of
  files/uk/web/javascript/reference/statements/for...of/index.md
Labels: translation

#366 translation(JS): web/javascript/reference/global_objects/array/some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: translation

#367 translation(JS): web/javascript/reference/global_objects/array/findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: translation

#411 hotfix/lang-check-skip-macros Skip example macros and few others
  scripts/utils/check-file.js
  scripts/utils/language-tool.js
Labels: bug

#407 Update/js ref
  files/uk/web/javascript/reference/index.md
Labels: update

#408 Update/js ref go
  files/uk/web/javascript/reference/index.md
Labels: update

#409 Update/js ref operators
  files/uk/web/javascript/reference/operators/index.md
Labels: update

#410 Update/js ref functions af
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#412 update(JS): web/javascript/reference/operators/destructuring_assignment
  files/uk/web/javascript/reference/operators/destructuring_assignment/index.md
  uk_spelling_additions.txt
Labels: translation, update
