Repository webdoky/content, pull requests merged in 2022-12, with the labels that each got.

#1034 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: translation, update

#1035 update(HTML): web/html/element/input/number
  files/uk/web/html/element/input/number/index.md
Labels: update

#1036 update(HTML): web/html/element/div
  files/uk/web/html/element/div/index.md
Labels: update

#1037 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: update

#1038 update(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
Labels: update

#1024 translation(CSS): web/css/align-items
  files/uk/web/css/align-items/index.md
Labels: translation

#919 translation(CSS): web/css/gradient/linear-gradient
  files/uk/web/css/gradient/linear-gradient/index.md
  files/uk/web/css/gradient/linear-gradient/linear-gradient.png
Labels: translation

#1017 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: translation, update

#1032 update(JS): web/javascript
  files/uk/web/javascript/index.md
Labels: translation, update

#1040 update(HTML): web/html/element/script
  files/uk/web/html/element/script/index.md
Labels: translation, update

#1041 update(HTML): web/html/element/label
  files/uk/web/html/element/label/index.md
Labels: translation, update

#1042 update(JS): web/javascript/closures
  files/uk/web/javascript/closures/index.md
Labels: update

#1043 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: update

#934 translation(JS): web/javascript/reference/global_objects/typeerror
  files/uk/web/javascript/reference/global_objects/typeerror/index.md
  uk_spelling_additions.txt
Labels: translation

#930 translation(CSS): web/css/initial_value
  files/uk/web/css/initial_value/index.md
  uk_spelling_additions.txt
Labels: translation

#911 update(JS): web/javascript/reference/global_objects/math/floor
  files/uk/web/javascript/reference/global_objects/math/floor/index.md
Labels: translation, update

#916 translation(Guide): web/guide/html/content_categories
  files/uk/web/guide/html/content_categories/content_categories_venn.png
  files/uk/web/guide/html/content_categories/index.md
Labels: translation

#922 translation(CSS): web/css/length
  files/uk/web/css/length/index.md
  uk_spelling_additions.txt
Labels: translation

#927 translation(CSS): web/css/number
  files/uk/web/css/number/index.md
Labels: translation

#928 translation(JS): web/javascript/reference/global_objects/nan
  files/uk/web/javascript/reference/global_objects/nan/index.md
  uk_spelling_additions.txt
Labels: translation

#929 translation(CSS): web/css/computed_value
  files/uk/web/css/computed_value/index.md
Labels: translation

#931 translation(CSS): web/css/inheritance
  files/uk/web/css/inheritance/index.md
  uk_spelling_additions.txt
Labels: translation

#932 translation(JS): web/javascript/reference/global_objects/undefined
  files/uk/web/javascript/reference/global_objects/undefined/index.md
  uk_spelling_additions.txt
Labels: translation

#1049 chore: docker container with name, caught exception, timeout with value
  scripts/check.js
  scripts/scrape.py
  scripts/utils/countdown.js
  scripts/utils/language-tool.js
Labels: bug, enhancement

#1048 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: update

#1050 update(JS): web/javascript/reference/global_objects/math
  files/uk/web/javascript/reference/global_objects/math/index.md
Labels: update

#1055 update(JS): web/javascript/reference/global_objects/math/max
  files/uk/web/javascript/reference/global_objects/math/max/index.md
Labels: update

#1056 update(JS): web/javascript/reference/global_objects/string/slice
  files/uk/web/javascript/reference/global_objects/string/slice/index.md
Labels: update

#1027 update(JS): web/javascript/reference/operators
  files/uk/web/javascript/reference/operators/index.md
Labels: translation, update

#1062 update(HTML): Web/HTML/Content_categories
  files/uk/web/html/content_categories/content_categories_venn.png
  files/uk/web/html/content_categories/index.md
Labels: bug, update

#1060 update(JS): web/javascript/reference/global_objects/array/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: translation, update

#1064 update(SVG): web/svg
  files/uk/web/svg/index.md
Labels: update

#1030 translation(JS): Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
  files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
Labels: translation

#935 translation(JS): web/javascript/reference/global_objects/regexp/exec
  files/uk/web/javascript/reference/global_objects/regexp/exec/index.md
Labels: translation

#938 translation(JS): web/javascript/guide/indexed_collections
  files/uk/web/javascript/guide/indexed_collections/index.md
Labels: translation

#1070 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update

#1086 update(JS): web/javascript/reference/global_objects/array/filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: update

#1087 update(JS): web/javascript/reference/global_objects/array/find
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: update

#1088 update(JS): web/javascript/reference/global_objects/array/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: update

#1089 update(JS): web/javascript/reference/global_objects/array/foreach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: update

#1090 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: update

#1091 update(JS): web/javascript/reference/operators
  files/uk/web/javascript/reference/operators/index.md
Labels: update

#1092 update(JS): web/javascript/reference/global_objects/array/slice
  files/uk/web/javascript/reference/global_objects/array/slice/index.md
Labels: update

#1094 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: update

#1100 update(JS): web/javascript/reference/global_objects/array/includes
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
Labels: update

#1099 update(JS): web/javascript/reference/global_objects/map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: update

#1098 update(JS): web/javascript/reference/operators/conditional_operator
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: update

#1096 update(JS): web/javascript/reference/global_objects/array/splice
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
Labels: update

#1095 update(JS): web/javascript/reference/global_objects/string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: update

#1103 update(JS): web/javascript/reference/global_objects/object/entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: update

#1104 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#1105 update(JS): web/javascript/reference/global_objects/object/keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: update

#1106 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#1108 update(JS): web/javascript/reference/global_objects
  files/uk/web/javascript/reference/global_objects/index.md
Labels: update

#1109 update(JS): web/javascript/reference/statements
  files/uk/web/javascript/reference/statements/index.md
Labels: update

#1110 update(JS): web/javascript/reference/global_objects/object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: update

#1111 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: update

#1112 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: update

#1113 update(JS): web/javascript/reference/statements/async_function
  files/uk/web/javascript/reference/statements/async_function/index.md
Labels: update

#1114 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: update

#1115 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: update

#1117 update(JS): web/javascript/reference/operators/typeof
  files/uk/web/javascript/reference/operators/typeof/index.md
Labels: update

#1118 update(JS): web/javascript/reference/global_objects/array/some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: update

#1121 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: update

#1122 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#1123 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: update

#1125 update(JS): web/javascript/reference/global_objects/json/parse
  files/uk/web/javascript/reference/global_objects/json/parse/index.md
Labels: update

#1073 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update

#1126 update(JS): web/javascript
  files/uk/web/javascript/index.md
Labels: update

#1107 update(JS): web/javascript/reference/global_objects/statements/import
  files/uk/web/javascript/reference/global_objects/math/random/index.md
  files/uk/web/javascript/reference/statements/import/index.md
Labels: update

#1127 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#1128 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#1129 update(JS): web/javascript/reference/global_objects/array/join
  files/uk/web/javascript/reference/global_objects/array/join/index.md
Labels: update

#1130 update(JS): web/javascript/data_structures
  files/uk/web/javascript/data_structures/index.md
Labels: update

#1131 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: update

#1132 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#1133 update(JS): web/javascript/reference/global_objects/string/match
  files/uk/web/javascript/reference/global_objects/string/match/index.md
Labels: update

#1144 update(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
Labels: update

#1147 update(JS): web/javascript/reference/global_objects/string/replaceall
  files/uk/web/javascript/reference/global_objects/string/replaceall/index.md
Labels: update

#1149 update(JS): web/javascript/guide
  files/uk/web/javascript/guide/index.md
Labels: update

#1148 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: update

#1150 update(JS): web/javascript/reference/global_objects/math/round
  files/uk/web/javascript/reference/global_objects/math/round/index.md
Labels: update

#1151 update(JS): web/javascript/guide/working_with_objects
  files/uk/web/javascript/guide/working_with_objects/index.md
Labels: update

#1152 update(JS): web/javascript/reference/statements/try...catch
  files/uk/web/javascript/reference/statements/try...catch/index.md
Labels: update

#1162 update(CSS): web/css/css_grid_layout/basic_concepts_of_grid_layout
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
Labels: update

#1165 update(HTML): web/html
  files/uk/web/html/index.md
Labels: update

#1173 update(JS): web/javascript/reference/global_objects/array/from
  files/uk/web/javascript/reference/global_objects/array/from/index.md
Labels: update

#1175 update(JS): web/javascript/reference/global_objects/string/slice
  files/uk/web/javascript/reference/global_objects/string/slice/index.md
Labels: update

#1174 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#1176 update(JS): web/javascript/reference/global_objects/string/includes
  files/uk/web/javascript/reference/global_objects/string/includes/index.md
Labels: update

#1177 update(JS): web/javascript/reference/global_objects/date/toisostring
  files/uk/web/javascript/reference/global_objects/date/toisostring/index.md
Labels: update

#1178 update(JS): web/javascript/reference/global_objects/array/shift
  files/uk/web/javascript/reference/global_objects/array/shift/index.md
Labels: update

#1179 update(JS): web/javascript/reference/global_objects/array/pop
  files/uk/web/javascript/reference/global_objects/array/pop/index.md
Labels: update

#1180 update(JS): web/javascript/reference/global_objects/math/max
  files/uk/web/javascript/reference/global_objects/math/max/index.md
Labels: update

#1181 update(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
Labels: update

#1182 update(JS): web/javascript/reference/global_objects/array/flat
  files/uk/web/javascript/reference/global_objects/array/flat/index.md
Labels: update

#1183 update(JS): web/javascript/reference/global_objects/math/floor
  files/uk/web/javascript/reference/global_objects/math/floor/index.md
Labels: update

#1184 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: update

#1185 update(JS): web/javascript/reference/global_objects/array/isarray
  files/uk/web/javascript/reference/global_objects/array/isarray/index.md
Labels: update

#1186 update(JS): web/javascript/reference/global_objects/date/date
  files/uk/web/javascript/reference/global_objects/date/date/index.md
Labels: update

#1187 update(JS): web/javascript/reference/global_objects/object/hasownproperty
  files/uk/web/javascript/reference/global_objects/object/hasownproperty/index.md
Labels: update

#1022 translation(CSS): web/css/transform-function/rotate
  files/uk/web/css/transform-function/rotate/index.md
Labels: translation

#1031 translation(CSS): web/css/calc
  files/uk/web/css/calc/index.md
Labels: translation

#1141 translation(JS): Web/JavaScript/Reference/Global_Objects/Object/fromEntries
  files/uk/web/javascript/reference/global_objects/object/fromentries/index.md
Labels: translation

#1039 translation(HTML): web/html/viewport_meta_tag
  files/uk/web/html/viewport_meta_tag/index.md
  uk_spelling_additions.txt
Labels: translation
