Repository webdoky/content, pull requests merged in 2022-01, with the labels that each got.

#150 feature: automated changelog update
  .github/workflows/main.yml
  updateChangelog.sh
Labels: enhancement

#155 translation(js): /Web/JavaScript/Reference/Functions/Arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: translation

#126 translation(JS): /Web/JavaScript/Reference/Global_Objects/Math/clz32
  files/uk/web/javascript/reference/global_objects/math/clz32/index.md
Labels: translation

#162 update(js): Web/JavaScript/Reference/Global_Objects/Array/forEach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: content

#160 update(js): Web/JavaScript/Reference/Global_Objects/Array/filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: translation, content

#147 translation(CSS): web/css/font-size/index.md
  files/uk/web/css/font-size/index.md
  uk_spelling_additions.txt
Labels: translation

#148 translation(CSS): css/background-image/index.md
  files/uk/web/css/background-image/index.md
Labels: translation

#152 translation(CSS): css/using_css_custom_properties/index.md
  files/uk/web/css/using_css_custom_properties/index.md
  uk_spelling_additions.txt
Labels: translation

#151 translation(CSS): css/cursor/index.md
  files/uk/web/css/cursor/index.md
  uk_spelling_additions.txt
Labels: translation

#156 translation(js): Web/JavaScript/Reference/Global_Objects/String/replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: translation

#157 translation(JS): Web/JavaScript/Reference/Global_Objects/String/String
  files/uk/web/javascript/reference/global_objects/string/string/index.md
Labels: translation

#159 translation(js): Web/JavaScript/Reference/Global_Objects/String/length
  files/uk/web/javascript/reference/global_objects/string/length/index.md
Labels: translation

#164 update(js): Web/JavaScript/Reference/Global_Objects/Array/Reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: translation, content

#166 feat: checking the uncommitted git diff only
  package.json
  scripts/check.js
  scripts/utils/execute.js
  yarn.lock
Labels: enhancement

#171 translation(js): Web/JavaScript/Reference/Global_Objects/String/big
  files/uk/web/javascript/reference/global_objects/string/big/index.md
Labels: translation

#169 translation(js): Web/JavaScript/Reference/Global_Objects/String/anchor
  files/uk/web/javascript/reference/global_objects/string/anchor/index.md
Labels: translation

#170 translation(js): Web/JavaScript/Reference/Global_Objects/String/at
  files/uk/web/javascript/reference/global_objects/string/at/index.md
Labels: translation

#172 translation(js): Web/JavaScript/Reference/Global_Objects/String/blink
  files/uk/web/javascript/reference/global_objects/string/blink/index.md
Labels: translation

#174 translation(js): Web/JavaScript/Reference/Global_Objects/String/charAt
  files/uk/web/javascript/reference/global_objects/string/charat/index.md
  uk_spelling_additions.txt
Labels: translation

#178 fix: make `check-diff` run for staged files too
  scripts/check.js
Labels: bug

#175 translation(CSS): css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
  files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
  uk_spelling_additions.txt
Labels: translation

#176 update(CSS): web/css/specificity/index.md
  files/uk/web/css/specificity/index.md
  scripts/check.js
  uk_ignore_additions.txt
Labels: bug, content

#177 update(CSS): web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
  files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
  uk_spelling_additions.txt
Labels: translation, content

#179 translation(CSS): web/css/font-family/index.md
  files/uk/web/css/font-family/index.md
  uk_ignore_additions.txt
Labels: translation

#185 chore: update links in js-string section
  files/uk/web/javascript/reference/global_objects/string/index.md
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: bug, content

#183 chore: update links and anchors in CSS section
  files/uk/web/css/-moz-orient/index.md
  files/uk/web/css/cursor/index.md
  files/uk/web/css/display/index.md
  files/uk/web/css/font-size/index.md
Labels: bug, content

#184 chore: update links in js-array section
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
  files/uk/web/javascript/reference/global_objects/array/find/index.md
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
  files/uk/web/javascript/reference/global_objects/array/index.md
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: bug, content

#186 chore: update links in JS section
  files/uk/web/javascript/guide/regular_expressions/index.md
  files/uk/web/javascript/reference/classes/index.md
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
  files/uk/web/javascript/reference/global_objects/map/index.md
  files/uk/web/javascript/reference/global_objects/math/pow/index.md
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: bug, content

#182 translation(CSS): web/css/media_queries/using_media_queries/index.md
  files/uk/web/css/media_queries/using_media_queries/index.md
  uk_spelling_additions.txt
Labels: translation

#187 translation(CSS): web/css/border/index.md
  files/uk/web/css/border/index.md
  uk_spelling_additions.txt
Labels: translation

#188 translation(CSS): web/css/background/index.md
  files/uk/web/css/background/index.md
Labels: translation

#189 translation(CSS): web/css/padding/index.md
  files/uk/web/css/padding/index.md
Labels: translation

#200 translation(js): Web/JavaScript/Reference/Global_Objects/String/fixed
  files/uk/web/javascript/reference/global_objects/string/fixed/index.md
Labels: translation

#205 translation(js): Web/JavaScript/Reference/Global_Objects/String/italics
  files/uk/web/javascript/reference/global_objects/string/italics/index.md
Labels: translation

#191 update(JS): web/javascript/reference/global_objects/index.md
  files/uk/web/javascript/reference/global_objects/index.md
Labels: translation, content

#192 update(JS): web/javascript/reference/global_objects/date/index.md
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, content

#193 update(JS): web/javascript/reference/global_objects/array/sort/index.md
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: translation, content

#196 translation(js): Web/JavaScript/Reference/Global_Objects/String/charCodeAt
  files/uk/web/javascript/reference/global_objects/string/charcodeat/index.md
  uk_spelling_additions.txt
Labels: translation

#197 translation(js): Web/JavaScript/Reference/Global_Objects/String/codePointAt
  files/uk/web/javascript/reference/global_objects/string/codepointat/index.md
Labels: translation

#198 translation(js): Web/JavaScript/Reference/Global_Objects/String/concat
  files/uk/web/javascript/reference/global_objects/string/concat/index.md
Labels: translation

#199 translation(js): Web/JavaScript/Reference/Global_Objects/String/endsWith
  files/uk/web/javascript/reference/global_objects/string/endswith/index.md
Labels: translation

#201 translation(js): Web/JavaScript/Reference/Global_Objects/String/fontcolor
  files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
Labels: translation

#202 translation(js): Web/JavaScript/Reference/Global_Objects/String/fontsize
  files/uk/web/javascript/reference/global_objects/string/fontsize/index.md
Labels: translation

#203 translation(js): Web/JavaScript/Reference/Global_Objects/String/includes
  files/uk/web/javascript/reference/global_objects/string/includes/index.md
Labels: translation

#204 translation(js): Web/JavaScript/Reference/Global_Objects/String/indexOf
  files/uk/web/javascript/reference/global_objects/string/indexof/index.md
Labels: translation

#206 translation(js): Web/JavaScript/Reference/Global_Objects/String/lastIndexOf
  files/uk/web/javascript/reference/global_objects/string/lastindexof/index.md
Labels: translation

#207 translation(js): Web/JavaScript/Reference/Global_Objects/String/link
  files/uk/web/javascript/reference/global_objects/string/link/index.md
Labels: translation

#194 translation(HTML): web/html/index.md
  files/uk/web/html/index.md
  uk_spelling_additions.txt
Labels: translation

#195 translation(HTML): web/html/element/index.md
  files/uk/web/html/element/index.md
  uk_spelling_additions.txt
Labels: translation

#110 translation(HTML): web/html/element/hr/index.md
  files/uk/web/html/element/hr/index.md
Labels: translation

#112 translation: Block-level elements
  files/uk/web/html/block-level_elements/index.md
Labels: translation
