Repository webdoky/content, pull requests merged in 2022-09, with the labels that each got.

#573 update(JS): web/javascript/reference/global_objects/string/replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: translation, update

#586 update(CSS): web/css
  files/uk/web/css/index.md
Labels: translation, update

#590 update(JS): web/javascript/reference/global_objects/array/map
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: translation, update

#591 update(JS): web/javascript/reference/global_objects/array/foreach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: update

#592 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#593 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
  uk_spelling_additions.txt
Labels: translation, update

#594 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: update

#595 update(JS): web/javascript/reference/global_objects/array/sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: update

#596 update(JS): web/javascript/reference/operators/conditional_operator
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: translation, update

#597 update(JS): web/javascript/reference/global_objects/map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: update

#598 update(JS): web/javascript/guide/regular_expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
Labels: translation, update

#599 update(JS): web/javascript/reference/global_objects/object/entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: update

#600 update(JS): web/javascript/reference/global_objects/array/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: translation, update

#601 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: translation, update

#602 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: update

#603 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: translation, update

#604 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: translation, update

#606 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#607 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#608 update(JS): web/javascript/reference/global_objects/array/find
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: update

#609 Update/js ref go string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update

#610 update(JS): web/javascript/reference/operators
  files/uk/web/javascript/reference/operators/index.md
Labels: update

#612 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#613 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: update

#614 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#615 update(JS): web/javascript/reference/statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
Labels: update

#619 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: update

#620 update(JS): web/javascript/reference/statements/async_function
  files/uk/web/javascript/reference/statements/async_function/index.md
Labels: update

#621 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: update

#622 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#611 update(JS): web/javascript/reference/global_objects/array/includes
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
Labels: translation, update

#617 update(JS): web/javascript/reference/global_objects/object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: translation, update

#618 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: update

#530 translation(HTML): web/html/element/script
  files/uk/web/html/element/script/index.md
  uk_ignore_additions.txt
  uk_spelling_additions.txt
Labels: translation

#623 update(JS): web/javascript/reference/global_objects/array/findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: update

#627 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#628 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: update

#630 Update/html element select 2
  files/uk/web/html/element/select/index.md
Labels: update

#632 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: update

#633 update(JS): web/javascript/reference/statements/switch
  files/uk/web/javascript/reference/statements/switch/index.md
Labels: update

#634 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: update

#636 update(CSS): web/css/justify-content
  files/uk/web/css/justify-content/index.md
Labels: update

#637 update(CSS): web/css/font-size
  files/uk/web/css/font-size/index.md
Labels: update

#638 update(CSS): web/css/border
  files/uk/web/css/border/index.md
Labels: update

#639 update(JS): web/javascript/reference/global_objects/string/substring
  files/uk/web/javascript/reference/global_objects/string/substring/index.md
Labels: update

#647 update(JS): web/javascript/reference/
  files/uk/web/javascript/reference/index.md
Labels: update

#648 update(CSS): web/css
  files/uk/web/css/index.md
Labels: update

#650 update(HTML): web/html
  files/uk/web/html/index.md
Labels: update

#651 update(HTML): web/html/element
  files/uk/web/html/element/index.md
Labels: update

#649 update(JS): web/javascript
  files/uk/web/javascript/index.md
Labels: translation, update

#652 update(JS): web/javascript/reference/global_objects/array/filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: update

#653 update(JS): web/javascript/reference/global_objects/array/map
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: update

#654 update(JS): web/javascript/reference/global_objects/array/foreach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: update

#655 update(JS): web/javascript/reference/global_objects/array/find
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: update

#656 update(JS): web/javascript/reference/global_objects/array/splice
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
Labels: update

#657 update(JS): web/javascript/reference/global_objects/array/slice
  files/uk/web/javascript/reference/global_objects/array/slice/index.md
Labels: update

#658 update(JS): web/javascript/reference/global_objects/array/sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: update

#659 update(JS): web/javascript/operators/conditional_operator
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: update

#660 update(JS): web/javascript/reference/global_objects/object/keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: update

#661 update(JS): web/javascript/reference/global_objects/array/includes
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
Labels: update

#662 update(JS): web/javascript/reference/global_objects/object/entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: update

#664 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#665 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: update

#666 update(JS): web/javascript/reference/global_objects/string/replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: update

#667 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: update

#669 update(JS): web/javascript/reference/global_objects/array/some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: update

#670 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: update

#663 update(JS): web/javascript/reference/global_objects/array/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: translation, update

#668 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
  uk_spelling_additions.txt
Labels: translation, update

#671 update(JS): web/javascript/reference/statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
Labels: translation, update

#672 update(CSS): web/css/specificity
  files/uk/web/css/specificity/index.md
Labels: update

#673 update(JS): web/javascript/reference/global_objects/map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: update

#674 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: update

#675 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: update

#676 update(JS): web/javascript/reference/global_objects/json/parse
  files/uk/web/javascript/reference/global_objects/json/parse/index.md
Labels: update

#677 update(JS): web/javascript/reference/global_objects/string/match
  files/uk/web/javascript/reference/global_objects/string/match/index.md
Labels: update

#679 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#678 update(JS): web/javascript/reference/statements/switch
  files/uk/web/javascript/reference/statements/switch/index.md
Labels: update

#680 update(JS): web/javascript/reference/global_objects/date/now
  files/uk/web/javascript/reference/global_objects/date/now/index.md
Labels: update

#681 update(JS): web/javascript/reference/operators/nullish_coalescing_operator
  files/uk/web/javascript/reference/operators/nullish_coalescing_operator/index.md
Labels: update

#682 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: update

#683 update(JS): web/javascript/reference/global_objects/string/substring
  files/uk/web/javascript/reference/global_objects/string/substring/index.md
Labels: update

#687 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: update

#688 update(JS): web/javascript/reference/operators/destructuring_assignment
  files/uk/web/javascript/reference/operators/destructuring_assignment/index.md
Labels: update

#624 update(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/index.md
Labels: translation, update

#626 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
  uk_spelling_additions.txt
Labels: translation, update

#629 update(HTML): web/html/element/input/date
  files/uk/web/html/element/input/date/index.md
Labels: translation, update

#631 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: translation, update

#640 update(JS): web/javascript/reference/global_objects/math
  files/uk/web/javascript/reference/global_objects/math/index.md
Labels: translation, update

#644 update(JS): web/javascript/reference/global_objects/math/round
  files/uk/web/javascript/reference/global_objects/math/round/index.md
Labels: translation, update

#689 update(JS): web/javascript/reference/statements/async_function
  files/uk/web/javascript/reference/statements/async_function/index.md
Labels: update

#690 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: update

#691 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#692 update(JS): web/javascript/reference/global_objects
  files/uk/web/javascript/reference/global_objects/index.md
Labels: update

#693 update(JS): web/javascript/reference/global_objects/array/findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: update

#694 update(JS): web/javascript/reference/global_objects/array/join
  files/uk/web/javascript/reference/global_objects/array/join/index.md
  uk_spelling_additions.txt
Labels: update

#695 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: update

#696 update(CSS): web/css/display
  files/uk/web/css/display/index.md
Labels: update

#697 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#685 translation(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
  uk_spelling_additions.txt
Labels: translation

#721 Restore missing misc files
  files/uk/web/css/background/starsolid.gif
  files/uk/web/css/position/long.jpeg
Labels: content

#722 translation(CSS): web/css/css_animations/using_css_animations
  files/uk/web/css/css_animations/using_css_animations/index.md
  uk_spelling_additions.txt
Labels: translation

#716 update(CSS): web/css/background
  files/uk/web/css/background/index.md
Labels: update

#732 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#733 update(JS): web/javascript/reference/global_objects
  files/uk/web/javascript/reference/global_objects/index.md
Labels: update

#734 update(CSS): web/css/specificity
  files/uk/web/css/specificity/index.md
Labels: update

#713 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#735 update(CSS): web/css/display
  files/uk/web/css/display/index.md
Labels: update

#737 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#708 update(JS): web/javascript/reference/global_objects/string/includes
  files/uk/web/javascript/reference/global_objects/string/includes/index.md
Labels: translation, update

#709 update(JS): web/javascript/reference/global_objects/math/max
  files/uk/web/javascript/reference/global_objects/math/max/index.md
Labels: translation, update

#738 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: update

#739 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: update

#740 update(JS): web/javascript/guide/regular_expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
Labels: update

#704 update(JS): web/javascript/guide
  files/uk/web/javascript/guide/index.md
  uk_spelling_additions.txt
Labels: update

#707 update(JS): web/javascript/reference/global_objects/string/slice
  files/uk/web/javascript/reference/global_objects/string/slice/index.md
Labels: update

#742 update(JS): web/javascript/reference/global_objects/array/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: update

#701 update(CSS): web/css/box-sizing
  files/uk/web/css/box-sizing/index.md
Labels: update

#743 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#744 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: update

#718 update(CSS): web/css/font-family
  files/uk/web/css/font-family/index.md
Labels: update

#745 update(CSS): web/css/css_flexible_box_layout/aligning_items_in_a_flex_container
  files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
Labels: update

#746 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#748 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: update

#749 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: update

#750 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: update

#751 update(CSS): web/css/height
  files/uk/web/css/height/index.md
Labels: update

#752 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
Labels: update

#754 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: update

#755 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: update

#625 update(JS): web/javascript/reference/statements/for...of
  files/uk/web/javascript/reference/statements/for...of/index.md
Labels: translation, update

#375 update(HTML): Web/HTML/Element/div/
  files/uk/web/html/element/div/index.md
Labels: update

#700 update(CSS): web/css/using_css_custom_properties
  files/uk/web/css/using_css_custom_properties/index.md
Labels: update

#699 update(CSS): web/css/css_flexible_box_layout/aligning_items_in_a_flex_container
  files/uk/web/css/using_css_custom_properties/index.md
Labels: update

#698 update(CSS): web/css/background-image
  files/uk/web/css/background-image/catfront.png
  files/uk/web/css/background-image/index.md
  files/uk/web/css/background-image/mdn_logo_only_color.png
  files/uk/web/css/background-image/startransparent.gif
  uk_spelling_additions.txt
Labels: update

#510 translation(JS): web/javascript/reference/statements/try...catch
  files/uk/web/javascript/reference/statements/try...catch/index.md
Labels: translation

#757 update(CSS): web/css/using_css_custom_properties
  files/uk/web/css/using_css_custom_properties/index.md
Labels: update

#758 update(CSS): web/css/background-image
  files/uk/web/css/background-image/index.md
Labels: update

#759 update(CSS): web/css/justify-content
  files/uk/web/css/justify-content/index.md
Labels: update

#760 update(CSS): web/css/media_queries/using_media_queries
  files/uk/web/css/media_queries/using_media_queries/index.md
Labels: update

#761 update(CSS): web/css/font-family
  files/uk/web/css/font-family/index.md
Labels: update

#762 update(HTML): web/html/element/script
  files/uk/web/html/element/script/index.md
Labels: update

#763 update(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
Labels: translation, update

#512 translation(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
  uk_spelling_additions.txt
Labels: translation

#528 translation(HTML): web/html/element/img
  .markdownlint-cli2.jsonc
  files/uk/web/html/element/img/clock-demo-200px.png
  files/uk/web/html/element/img/clock-demo-400px.png
  files/uk/web/html/element/img/favicon144.png
  files/uk/web/html/element/img/favicon72.png
  files/uk/web/html/element/img/index.md
  uk_spelling_additions.txt
Labels: translation

#529 translation(HTML): web/html/element/heading_elements
  files/uk/web/html/element/heading_elements/index.md
  uk_spelling_additions.txt
Labels: translation

#582 translation(JS): web/javascript/reference/global_objects/object/values
  files/uk/web/javascript/reference/global_objects/object/values/index.md
Labels: translation

#642 translation(JS): web/javascript/reference/global_objects/date/parse
  files/uk/web/javascript/reference/global_objects/date/parse/index.md
Labels: translation

#736 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#741 update(JS): web/javascript/reference/global_objects/string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update
