Repository webdoky/content, pull requests merged in 2022-07, with the labels that each got.

#416 update(CSS): web/css/width
  files/uk/web/css/width/index.md
Labels: update

#415 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: update

#380 update(CSS): Web/CSS/height/
  files/uk/web/css/height/index.md
Labels: translation, update

#379 update(CSS): Web/CSS/font-size/
  files/uk/web/css/font-size/index.md
Labels: update

#372 update(HTML): Web/HTML/Element/ul/
  files/uk/web/html/element/ul/index.md
Labels: update

#378 update(CSS): Web/CSS/font-family/
  files/uk/web/css/font-family/index.md
Labels: update

#419 Update/js ref go object keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: update

#418 Update/html element input
  files/uk/web/html/element/input/index.md
Labels: translation, update

#421 chore: fix broken definition list and anchors
  files/uk/web/html/element/input/index.md
Labels: bug

#422 translation(JS): web/javascript/reference/global_objects/array/join
  files/uk/web/javascript/reference/global_objects/array/join/index.md
Labels: translation

#370 translation(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
  uk_spelling_additions.txt
Labels: translation

#423 Update/js ref go
  files/uk/web/javascript/reference/global_objects/index.md
Labels: update

#400 translation(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
  uk_spelling_additions.txt
Labels: translation

#424 translation(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: translation

#429 Update/js
  files/uk/web/javascript/index.md
Labels: translation, update

#430 Update/js ref go array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: translation, update

#435 Update/js ref go date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, update

#413 translation(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: translation

#436 Update/js ref go array sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: translation, update

#439 Update/js ref go map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: translation, update

#371 update(JS): Web/JavaScript/Reference/Global_Objects/Promise/
  files/uk/web/javascript/reference/global_objects/promise/index.md
  uk_spelling_additions.txt
Labels: update

#414 translation(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/index.md
Labels: translation

#426 translation(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
  files/uk/web/html/element/input/radio/old-radio.jpg
  uk_spelling_additions.txt
Labels: translation

#441 Update/js ref go object entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: update

#381 update(CSS): Web/CSS/justify-content/
  files/uk/web/css/justify-content/index.md
Labels: update

#382 update(CSS): Web/CSS/padding/
  files/uk/web/css/padding/index.md
Labels: update

#384 update(CSS): Web/CSS/Using_CSS_custom_properties/
  files/uk/web/css/using_css_custom_properties/index.md
Labels: update

#386 update(CSS): Web/CSS/--*/
  files/uk/web/css/--_star_/index.md
Labels: update

#387 update(CSS): Web/CSS/-moz-image-rect/
  files/uk/web/css/-moz-image-rect/index.md
Labels: update

#389 update(CSS): Web/CSS/-moz-outline-radius-bottomleft/
  files/uk/web/css/-moz-outline-radius-bottomleft/index.md
Labels: update

#390 update(CSS): Web/CSS/-moz-outline-radius-bottomright/
  files/uk/web/css/-moz-outline-radius-bottomright/index.md
Labels: update

#391 update(CSS): Web/CSS/-moz-outline-radius-topleft/
  files/uk/web/css/-moz-outline-radius-topleft/index.md
Labels: update

#392 update(CSS): Web/CSS/-moz-outline-radius-topright/
  files/uk/web/css/-moz-outline-radius-topright/index.md
Labels: update

#394 update(CSS): Web/CSS/background-image/
  files/uk/web/css/background-image/index.md
Labels: update

#395 update(CSS): Web/CSS/background/
  files/uk/web/css/background/index.md
Labels: update

#398 update(CSS): Web/CSS/box-sizing/
  files/uk/web/css/box-sizing/index.md
Labels: update

#443 Update/css position
  files/uk/web/css/position/index.md
  uk_spelling_additions.txt
Labels: update

#444 Update/js ref go string split
  disabled_rules.txt
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: translation, update

#445 Update/js ref classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#446 Update/js ref go string replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: update

#448 update(JS): web/javascript/reference/statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
Labels: update

#396 update(CSS): Web/CSS/border/
  files/uk/web/css/border/index.md
Labels: update

#449 Update/js ref
  files/uk/web/javascript/reference/index.md
Labels: update

#450 Update/js ref go map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: translation, update

#451 Update/js ref go object keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: update

#453 update(JS): web/javascript/reference/operators/typeof
  files/uk/web/javascript/reference/operators/typeof/index.md
Labels: translation, update

#455 Replace left quote as apostrophe in spelling additions
  uk_spelling_additions.txt
Labels: bug

#447 Update/js ref functions af
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: translation, update

#452 Update/js ref operators
  files/uk/web/javascript/reference/operators/index.md
Labels: translation, update

#457 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#461 update(JS): web/javascript/reference/global_objects/array/findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: translation, update

#458 translation(JS): web/javascript/reference/statements
  files/uk/web/javascript/reference/statements/index.md
Labels: translation

#463 update(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/index.md
Labels: translation, update

#459 update(CSS): web/css/font-size
  files/uk/web/css/font-size/index.md
Labels: update

#460 update(CSS): web/css/media_queries/using_media_queries
  files/uk/web/css/media_queries/using_media_queries/index.md
Labels: update

#462 translation(JS): web/javascript/reference/global_objects/json/parse
  files/uk/web/javascript/reference/global_objects/json/parse/index.md
Labels: translation

#464 update(JS): web/javascript/reference/statements/for...of
  files/uk/web/javascript/reference/statements/for...of/index.md
Labels: update

#428 translation(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
  uk_ignore_additions.txt
  uk_spelling_additions.txt
Labels: translation

#465 translation(JS): web/javascript/reference/statements/switch
  files/uk/web/javascript/reference/statements/switch/index.md
Labels: translation

#467 Update/js ref go string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update

#469 translation(JS): web/javascript/reference/global_objects/date/now
  files/uk/web/javascript/reference/global_objects/date/now/index.md
  uk_spelling_additions.txt
Labels: translation

#468 translation(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
  uk_spelling_additions.txt
Labels: translation

#472 Update/js ref go array splice
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
Labels: update

#473 Update/js ref go array sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: update

#475 Update/js ref go string split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: update

#476 Update/js ref go string replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: update

#477 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
  uk_spelling_additions.txt
Labels: translation, update

#480 Update/js ref go array map
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: update

#481 Update/js ref go array foreach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: update

#482 Update/js ref go array find
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: update

#484 Update/js ref go string split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: update

#485 Translation/js ref go array some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: update

#483 Update/js ref go array reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: translation, update

#486 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#487 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: update

#488 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: update

#489 Update/js ref go array findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: update

#490 Update/css cursor
  files/uk/web/css/cursor/index.md
Labels: update

#491 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: update

#479 Update/js ref go array filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: update

#466 translation(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
  scripts/utils/check-file.js
  uk_spelling_additions.txt
Labels: translation

#471 translation(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
  uk_spelling_additions.txt
Labels: translation

#478 update(JS): web/javascript/reference/operators/destructuring_assignment
  files/uk/web/javascript/reference/operators/destructuring_assignment/index.md
  uk_spelling_additions.txt
Labels: translation, update

#492 update(JS): web/javascript/reference/global_objects/string/match
  files/uk/web/javascript/reference/global_objects/string/match/index.md
Labels: translation, update

#493 update(JS): web/javascript/reference/statements/switch
  files/uk/web/javascript/reference/statements/switch/index.md
Labels: translation, update

#495 Update/js ref go string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: update

#496 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: update

#500 Update/js ref go promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: update

#502 Update/js ref go array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#503 update(HTML): web/html/element
  files/uk/web/html/element/index.md
Labels: update

#505 Update/js ref go array sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: update

#506 Update/js ref go json stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#507 Update/css box shadow 2
  files/uk/web/css/box-shadow/index.md
Labels: update

#508 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#509 update(JS): web/reference/global_objects/string/replaceall
  files/uk/web/javascript/reference/global_objects/string/replaceall/index.md
Labels: update

#501 Update/css specificity
  files/uk/web/css/specificity/index.md
Labels: update

#504 Update/html element input
  files/uk/web/html/element/input/index.md
Labels: update

#513 Update/js ref
  files/uk/web/javascript/reference/index.md
Labels: update

#514 Update/js ref go array filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: update

#516 Update/js ref go json stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#517 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: update

#518 Update/js ref f arrow functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#519 update(JS): web/javascript/reference/global_objects/object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: update

#520 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#521 update(HTML): web/html/element/input/date
  files/uk/web/html/element/input/date/index.md
Labels: update

#522 Update/js ref go string match
  files/uk/web/javascript/reference/global_objects/string/match/index.md
Labels: update

#523 update(CSS): web/css/css_flexible_box_layout/basic_concepts_of_flexbox
  files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
Labels: update

#524 update(CSS): web/css/media_queries/using_media_queries
  files/uk/web/css/media_queries/using_media_queries/index.md
Labels: update

#525 Fix duplicated quotes in checked text
  scripts/utils/check-file.js
Labels: bug

#527 chore: gitignore .DS_Store
  .gitignore
Labels: bug

#515 Update/js ref go string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: update
