Repository webdoky/content, pull requests merged in 2022-10, with the labels that each got.

#830 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: update

#831 update(CSS): web/css/font-weight
  files/uk/web/css/font-weight/index.md
Labels: update

#832 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#834 update(CSS): web/css/background
  files/uk/web/css/background/index.md
Labels: update

#833 update(CSS): web/css/overflow
  files/uk/web/css/overflow/index.md
Labels: update

#835 update(CSS): web/css/css_animations/using_css_animations
  files/uk/web/css/css_animations/using_css_animations/index.md
Labels: update

#720 translation(CSS): web/css/css_transitions/using_css_transitions
  files/uk/web/css/css_transitions/using_css_transitions/index.md
  files/uk/web/css/css_transitions/using_css_transitions/tf_with_output_gt_than_1.png
  files/uk/web/css/css_transitions/using_css_transitions/transitionsprinciple.png
  uk_spelling_additions.txt
Labels: translation

#724 translation(CSS): web/css/margin
  files/uk/web/css/margin/index.md
Labels: translation

#727 translation(CSS): web/css/flex
  files/uk/web/css/flex/index.md
Labels: translation

#728 translation(CSS): web/css/_colon_nth-child
  files/uk/web/css/_colon_nth-child/index.md
Labels: translation

#729 translation(CSS): web/css/text-overflow
  files/uk/web/css/text-overflow/index.md
Labels: translation

#772 translation(CSS): web/css/css_backgrounds_and_borders/resizing_background_images
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/favicon57.de33179910ae.1.1.png
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/index.md
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/s.codepen.io_richienb_debug_lonxgp_pnkvygvggyxa.png
Labels: translation

#773 translation(CSS): web/css/text-decoration
  files/uk/web/css/text-decoration/index.md
Labels: translation

#776 translation(CSS): web/css/reference
  files/uk/web/css/reference/index.md
Labels: translation

#840 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: update

#806 translation(HTML): web/html/element/span
  files/uk/web/html/element/span/index.md
Labels: translation

#807 translation(HTML): web/html/element/p
  files/uk/web/html/element/p/index.md
Labels: translation

#778 translation(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: translation

#847 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: update

#850 update(JS): web/javascript/reference/global_objects/string/trim
  files/uk/web/javascript/reference/global_objects/string/trim/index.md
Labels: update

#848 Update Markdownlint config
  .markdownlint-cli2.jsonc
Labels: enhancement

#771 translation(CSS): web/css/line-height
  files/uk/web/css/line-height/index.md
Labels: translation

#777 translation(HTML): web/html/element/br
  files/uk/web/html/element/br/index.md
Labels: translation

#841 translation(JS): web/javascript/reference/global_objects/array/pop
  files/uk/web/javascript/reference/global_objects/array/pop/index.md
Labels: translation

#844 translation(JS): web/javascript/reference/global_objects/array/length
  files/uk/web/javascript/reference/global_objects/array/length/index.md
  uk_spelling_additions.txt
Labels: translation

#797 translation(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
  uk_spelling_additions.txt
Labels: translation

#808 translation(HTML): web/html/global_attributes
  files/uk/web/html/global_attributes/index.md
  uk_spelling_additions.txt
Labels: translation

#809 translation(HTML): web/html/element/textarea
  files/uk/web/html/element/textarea/index.md
Labels: translation

#836 translation(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
  uk_spelling_additions.txt
Labels: translation

#837 translation(JS): web/javascript/reference/global_objects/date/toisostring
  files/uk/web/javascript/reference/global_objects/date/toisostring/index.md
Labels: translation

#843 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: translation, update

#845 translation(JS): web/javascript/reference/global_objects/encodeuricomponent
  files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
Labels: translation

#852 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#849 translation(JS): web/javascript/guide/using_promises
  files/uk/web/javascript/guide/using_promises/index.md
  uk_spelling_additions.txt
Labels: translation

#839 translation(JS): web/javascript/reference/global_objects/date/date
  files/uk/web/javascript/reference/global_objects/date/date/index.md
Labels: translation

#853 update(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
Labels: translation, update

#858 update(JS): web/javascript/reference/global_objects/array/filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: translation, update

#859 update(JS): web/javascript/reference/global_objects/array/map
  files/uk/web/javascript/reference/global_objects/array/map/index.md
  uk_spelling_additions.txt
Labels: translation, update

#498 translation(JS): web/javascript/reference/statements/import
  files/uk/web/javascript/reference/statements/import/index.md
  uk_spelling_additions.txt
Labels: translation

#873 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#875 update(JS): web/javascript/reference/global_objects/date/now
  files/uk/web/javascript/reference/global_objects/date/now/index.md
Labels: update

#851 translation(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
  uk_spelling_additions.txt
Labels: translation

#862 update(JS): web/javascript/reference/global_objects/array/splice
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
  uk_spelling_additions.txt
Labels: translation, update

#856 translation(JS): Web/JavaScript/Guide/Working_with_Objects
  files/uk/web/javascript/guide/working_with_objects/index.md
Labels: translation

#886 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#887 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: update

#868 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: translation, update

#869 update(JS): web/javascript/reference/global_objects/array/some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: translation, update

#871 update(JS): web/javascript/reference/global_objects/array/findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: translation, update

#872 update(JS): web/javascript/reference/global_objects/array/join
  files/uk/web/javascript/reference/global_objects/array/join/index.md
Labels: translation, update

#876 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: translation, update

#878 update(JS): web/javascript/reference/global_objects/array/from
  files/uk/web/javascript/reference/global_objects/array/from/index.md
  uk_spelling_additions.txt
Labels: translation, update

#877 update(JS): web/javascript/reference/statements/try...catch
  files/uk/web/javascript/reference/statements/try...catch/index.md
Labels: translation, update

#881 update(JS): web/javascript/reference/global_objects/array/flat
  files/uk/web/javascript/reference/global_objects/array/flat/index.md
Labels: translation, update

#883 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update

#888 update(HTML): web/html/element/br
  files/uk/web/html/element/br/index.md
Labels: update

#889 update(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
Labels: update

#882 translation(Glossary): glossary
  files/uk/glossary/index.md
  uk_spelling_additions.txt
Labels: translation

#711 translation(CSS): web/css/grid-template-columns
  files/uk/web/css/grid-template-columns/index.md
  uk_spelling_additions.txt
Labels: translation

#717 translation(CSS): web/css/css_grid_layout
  files/uk/web/css/css_grid_layout/index.md
  uk_spelling_additions.txt
Labels: translation

#775 translation(CSS): web/css/css_grid_layout/basic_concepts_of_grid_layout
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/1-grid-inspector.png
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/1_diagram_numbered_grid_lines.png
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/1_grid_area.png
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/1_grid_cell.png
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/1_grid_track.png
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/1_nested_grids_in_flow.png
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
  uk_spelling_additions.txt
Labels: translation

#894 update(CSS): web/css/specificity
  files/uk/web/css/specificity/index.md
Labels: translation, update

#895 Internal links counter
  scripts/scrape.py
Labels: enhancement

#899 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: update

#901 update(JS): web/javascript/reference/global_objects/number
  files/uk/web/javascript/reference/global_objects/number/index.md
Labels: update

#912 Fix script
  scripts/scrape.py
Labels: bug

#904 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#906 update(CSS): web/css/css_transitions/using_css_transitions
  files/uk/web/css/css_transitions/using_css_transitions/index.md
Labels: update

#907 update(CSS): web/css/margin
  files/uk/web/css/margin/index.md
Labels: update

#910 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#909 update(JS): web/javascript/reference/global_objects/date/date
  files/uk/web/javascript/reference/global_objects/date/date/index.md
Labels: update

#855 translation(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
  uk_spelling_additions.txt
Labels: translation

#857 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
  uk_spelling_additions.txt
Labels: translation, update

#864 update(JS): web/javascript/reference/global_objects/array/sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
  uk_spelling_additions.txt
Labels: translation, update

#870 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: translation, update

#914 purge(CSS): web/css/-moz-context-properties
  files/uk/web/css/-moz-context-properties/index.md
Labels: update

#884 translation(JS): web/javascript/reference/global_objects/object/hasownproperty
  files/uk/web/javascript/reference/global_objects/object/hasownproperty/index.md
Labels: translation

#885 translation(JS): web/javascript/reference/global_objects/promise/then
  files/uk/web/javascript/reference/global_objects/promise/then/index.md
  uk_spelling_additions.txt
Labels: translation

#874 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: translation, update
