Repository webdoky/content, pull requests merged in 2023-02, with the labels that each got.

#1277 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: update

#1276 update(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
Labels: update

#1275 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: translation, update

#1280 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: update

#1281 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: update

#1282 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#1283 update(HTML): web/html/element/input/number
  files/uk/web/html/element/input/number/index.md
Labels: update

#1284 update(JS): web/javascript/reference/global_objects/array/isarray
  files/uk/web/javascript/reference/global_objects/array/isarray/index.md
Labels: update

#1102 translation(CSS): web/css/css_box_model/introduction_to_the_css_box_model
  files/uk/web/css/css_box_model/introduction_to_the_css_box_model/boxmodel-(3).png
  files/uk/web/css/css_box_model/introduction_to_the_css_box_model/index.md
Labels: translation

#1164 translation(CSS): web/css/text-transform
  files/uk/web/css/text-transform/index.md
  uk_ignore_additions.txt
  uk_spelling_additions.txt
Labels: translation

#1168 translation(CSS): web/css/backdrop-filter
  files/uk/web/css/backdrop-filter/anemones.jpg
  files/uk/web/css/backdrop-filter/index.md
Labels: translation

#1188 translation(JS): web/javascript/reference/global_objects/array/reverse
  files/uk/web/javascript/reference/global_objects/array/reverse/index.md
Labels: translation

#1271 translation(Glossary): glossary/truthy
  files/uk/glossary/truthy/index.md
Labels: translation

#1155 translation(CSS): web/css/white-space
  files/uk/web/css/white-space/index.md
Labels: translation

#1170 translation(CSS): web/css/flex-direction
  files/uk/web/css/flex-direction/index.md
Labels: translation

#1156 translation(CSS): web/css/css_text/wrapping_text
  files/uk/web/css/css_text/wrapping_text/index.md
Labels: translation

#1192 translation(JS): web/javascript/reference/global_objects/promise/resolve
  files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
  uk_spelling_additions.txt
Labels: translation

#1218 translation(Glossary): glossary/user_agent
  files/uk/glossary/user_agent/index.md
Labels: translation

#1273 translation(JS): web/javascript/reference/global_objects/regexp/test
  files/uk/web/javascript/reference/global_objects/regexp/test/index.md
Labels: translation

#1278 translation(JS): web/javascript/reference/global_objects/regexp/lastindex
  files/uk/web/javascript/reference/global_objects/regexp/lastindex/index.md
Labels: translation

#1285 update(CSS): web/css/background
  files/uk/web/css/background/index.md
Labels: translation, update

#1213 translation(JS): web/javascript/reference/errors/not_defined
  files/uk/web/javascript/reference/errors/not_defined/index.md
Labels: translation

#1287 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#1295 update(CSS): web/css/vertical-align
  files/uk/web/css/vertical-align/index.md
Labels: update

#1293 update(JS): web/javascript/reference/global_objects/string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: update

#1294 update(CSS): web/css/box-shadow
  files/uk/web/css/box-shadow/index.md
Labels: translation, update

#1193 translation(JS): web/javascript/reference/operators/await
  files/uk/web/javascript/reference/operators/await/index.md
  uk_spelling_additions.txt
Labels: translation

#1214 translation(JS): web/javascript/guide/regular_expressions/cheatsheet
  files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
  uk_spelling_additions.txt
Labels: translation

#1216 translation(JS): web/javascript/reference/global_objects/intl/numberformat
  files/uk/web/javascript/reference/global_objects/intl/numberformat/index.md
Labels: translation

#1217 translation(JS): web/javascript/reference/global_objects/symbol
  files/uk/web/javascript/reference/global_objects/symbol/index.md
  uk_spelling_additions.txt
Labels: translation

#1219 translation(JS): web/javascript/reference/iteration_protocols
  files/uk/web/javascript/reference/iteration_protocols/index.md
  uk_spelling_additions.txt
Labels: translation

#1220 translation(CSS): web/css/containing_block
  files/uk/web/css/containing_block/box-model.png
  files/uk/web/css/containing_block/index.md
  uk_spelling_additions.txt
Labels: translation

#1298 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: update

#1299 update(JS): web/javascript/reference/global_objects/date/toisostring
  files/uk/web/javascript/reference/global_objects/date/toisostring/index.md
Labels: update

#1301 update(JS): web/javascript/reference/global_objects/array/isarray
  files/uk/web/javascript/reference/global_objects/array/isarray/index.md
Labels: update

#1297 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: translation, update

#1304 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#1154 translation(JS): Web/JavaScript/Reference/Global_Objects/Object/create
  files/uk/web/javascript/reference/global_objects/object/create/index.md
  uk_ignore_additions.txt
Labels: translation

#1292 translation(CSS): web/css/z-index
  files/uk/web/css/z-index/index.md
  uk_spelling_additions.txt
Labels: translation

#1296 translation(CSS): web/css/flex-wrap
  files/uk/web/css/flex-wrap/index.md
Labels: translation

#1288 translation(CSS): web/css/css_selectors
  files/uk/web/css/css_selectors/index.md
Labels: translation

#1291 translation(CSS): web/css/border-style
  files/uk/web/css/border-style/index.md
Labels: translation

#1309 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#1312 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#1315 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#1316 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#1317 update(CSS): web/css/margin
  files/uk/web/css/margin/index.md
Labels: update

#1319 update(CSS): web/css/display
  files/uk/web/css/display/index.md
Labels: update

#1332 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#1330 update(JS): web/javascript/reference/global_objects/array/filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: update

#1329 update(JS): web/javascript/reference/global_objects/array/map
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: update

#1328 update(HTML): web/html
  files/uk/web/html/index.md
Labels: update

#1326 update(CSS): web/css
  files/uk/web/css/index.md
Labels: update

#1325 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#1324 update(JS): web/javascript
  files/uk/web/javascript/index.md
Labels: update

#1323 update(JS): web/javascript/reference/global_objects
  files/uk/web/javascript/reference/global_objects/index.md
Labels: update

#1335 update(CSS): web/css
  files/uk/web/css/index.md
Labels: update

#1336 update(HTML): web/html
  files/uk/web/html/index.md
Labels: update

#1337 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#1338 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#1339 update(JS): web/javascript/reference/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: update

#1340 update(JS): web/javascript/reference/global_objects/array/foreach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: update

#1341 update(JS): web/javascript/reference/global_objects/array/sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: update

#1343 update(JS): web/javascript/reference/global_objects/array/slice
  files/uk/web/javascript/reference/global_objects/array/slice/index.md
Labels: update

#1344 update(JS): web/javascript/reference/operators
  files/uk/web/javascript/reference/operators/index.md
Labels: update

#1345 update(CSS): web/css/css_flexbox_layout/alignign_items_in_a_flex_container
  files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
Labels: update

#1347 update(JS): web/javascript/reference/global_objects/array/splice
  files/uk/web/javascript/reference/global_objects/array/splice/index.md
Labels: update

#1348 update(JS): web/javascript/guide/regular_expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
Labels: update

#1349 update(JS): web/javascript/reference/operators/conditional_operator
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: update

#1351 update(JS): web/javascript/reference/global_objects/array/includes
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
Labels: update

#1350 update(JS): web/javascript/reference/global_objects/string/replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: update

#1355 update(JS): web/javascript/reference/global_objects/object/keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: update

#1356 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: update

#1354 update(CSS): web/css/position
  files/uk/web/css/position/index.md
Labels: update

#1352 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#1342 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, update

#1346 update(JS): web/javascript/reference/global_objects/string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update
