Repository webdoky/content, pull requests merged in 2023-04, with the labels that each got.

#1592 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: update

#1593 update(JS): web/javascript/guide/using_promises
  files/uk/web/javascript/guide/using_promises/index.md
Labels: update

#1594 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#1602 Chore/rewrite finishupdate to js
  files/uk/web/test2/index.md
  package.json
  scripts/check.js
  scripts/finishupdate.js
  scripts/finishupdate.sh
  scripts/gotobranch.sh
  scripts/startupdate.sh
  scripts/utils/does-git-branch-exist-locally.js
  scripts/utils/does-git-branch-exist-on-remote.js
  scripts/utils/execute.js
Labels: enhancement

#1604 Chore/fix finishupdate js
  scripts/finishupdate.js
Labels: bug

#1612 update(HTML): web/html/element/input/date
  files/uk/web/html/element/input/date/index.md
Labels: update

#1613 update(JS): web/javascript/guide/regular_expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
Labels: update

#1614 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#1616 update(JS): web/javascript/reference/global_objects/array/find
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: update

#1617 update(JS): web/javascript/reference/global_objects/array/foreach
  files/uk/web/javascript/reference/global_objects/array/foreach/index.md
Labels: update

#1607 update(JS): web/javascript/guide/working_with_objects
  files/uk/web/javascript/guide/working_with_objects/index.md
Labels: update

#1619 update(CSS): web/css/display
  files/uk/web/css/display/index.md
Labels: update

#1620 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: update

#1621 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: update

#1622 update(CSS): web/css/css_transitions/using_css_transitions
  files/uk/web/css/css_transitions/using_css_transitions/index.md
Labels: update

#1623 update(CSS): web/css
  files/uk/web/css/index.md
Labels: update

#1625 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#1626 update(HTML): web/html/element/select
  files/uk/web/html/element/select/index.md
Labels: update

#1627 update(JS): web/javascript/reference/global_objects/array/filter
  files/uk/web/javascript/reference/global_objects/array/filter/index.md
Labels: update

#1628 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: update

#1629 update(JS): web/javascript/data_structures
  files/uk/web/javascript/data_structures/index.md
Labels: update

#1630 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: update

#1631 update(JS): web/javascript/reference/global_objects/string/replace
  files/uk/web/javascript/reference/global_objects/string/replace/index.md
Labels: update

#1632 update(CSS): web/css/css_grid_layout/basic_concepts_of_grid_layout
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
Labels: update

#1633 update(JS): web/javascript/reference/operators
  files/uk/web/javascript/reference/operators/index.md
Labels: update

#1638 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: update

#1639 update(JS): web/javascript/reference/global_objects/array/map
  files/uk/web/javascript/reference/global_objects/array/map/index.md
Labels: update

#1640 update(HTML): web/html/element/div
  files/uk/web/html/element/div/index.md
Labels: update

#1635 translation(JS): Web/JavaScript/Reference/Global_Objects/Object/freeze
  files/uk/web/javascript/reference/global_objects/object/freeze/index.md
  uk_spelling_additions.txt
Labels: translation

#1643 update(HTML): web/html/element/p
  files/uk/web/html/element/p/index.md
Labels: update

#1648 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#1649 update(JS): web/javascript/guide/indexed_collections
  files/uk/web/javascript/guide/indexed_collections/index.md
Labels: update

#1650 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: update

#1651 update(JS): web/javascript/reference/global_objects/date/tolocaledatestring
  files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
Labels: update

#1652 update(JS): web/javascript/reference/global_objects/object/hasownproperty
  files/uk/web/javascript/reference/global_objects/object/hasownproperty/index.md
Labels: update

#1646 update(JS): web/javascript/reference/global_objects/array/includes
  files/uk/web/javascript/reference/global_objects/array/includes/index.md
Labels: update

#1506 update(JS): web/javascript/reference/global_objects/math/pow
  files/uk/web/javascript/reference/global_objects/math/pow/index.md
Labels: translation, update

#1507 update(HTML): web/html/element/ul
  files/uk/web/html/element/ul/index.md
Labels: translation, update

#1508 update(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
Labels: translation, update

#1515 update(JS): web/javascript/reference/global_objects/math/abs
  files/uk/web/javascript/reference/global_objects/math/abs/index.md
Labels: translation, update

#1516 update(JS): web/javascript/reference/global_objects/math/min
  files/uk/web/javascript/reference/global_objects/math/min/index.md
Labels: translation, update

#1533 update(CSS): web/css/--_star_
  files/uk/web/css/--_star_/index.md
Labels: translation, update

#1552 update(JS): web/javascript/reference/global_objects/string/localecompare
  files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
Labels: translation, update

#1658 update(HTML): web/html/element/label
  files/uk/web/html/element/label/index.md
Labels: update

#1660 update(CSS): web/css/text-decoration
  files/uk/web/css/text-decoration/index.md
Labels: update

#1661 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: update

#1662 update(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
Labels: update

#1663 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#1664 update(JS): web/javascript/reference/statements/async_function
  files/uk/web/javascript/reference/statements/async_function/index.md
Labels: update

#1665 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#1666 update(CSS): web/css/background
  files/uk/web/css/background/index.md
Labels: update

#1672 chore: revert markdownlint-rule-search-replace to 1.0.9
  package.json
  yarn.lock
Labels: bug

#1656 update(CSS): web/css/length
  files/uk/web/css/length/index.md
Labels: update

#1670 update(CSS): web/css/background-image
  files/uk/web/css/background-image/index.md
Labels: update

#1674 update(JS): web/javascript/reference/statements/import
  files/uk/web/javascript/reference/statements/import/index.md
Labels: update

#1675 update(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
Labels: update

#1679 update(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
Labels: update

#1680 update(JS): web/javascript/reference/global_objects/string/includes
  files/uk/web/javascript/reference/global_objects/string/includes/index.md
Labels: update

#1681 update(JS): web/javascript/reference/global_objects/string/match
  files/uk/web/javascript/reference/global_objects/string/match/index.md
Labels: update

#1682 update(JS): web/javascript/reference/global_objects/string/touppercase
  files/uk/web/javascript/reference/global_objects/string/touppercase/index.md
Labels: update

#1519 update(HTML): web/html/element/textarea
  files/uk/web/html/element/textarea/index.md
Labels: translation, update

#1523 update(JS): web/javascript/reference/global_objects/math/sign
  files/uk/web/javascript/reference/global_objects/math/sign/index.md
Labels: translation, update

#1525 update(JS): web/javascript/reference/global_objects/nan
  files/uk/web/javascript/reference/global_objects/nan/index.md
Labels: translation, update

#1528 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: translation, update

#1541 update(JS): web/javascript/reference/global_objects/math/ceil
  files/uk/web/javascript/reference/global_objects/math/ceil/index.md
Labels: translation, update

#1546 update(JS): web/javascript/reference/global_objects/math/sin
  files/uk/web/javascript/reference/global_objects/math/sin/index.md
Labels: translation, update
