Repository webdoky/content, pull requests merged in 2023-01, with the labels that each got.

#1158 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#1195 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#1196 update(CSS): web/css/display
  files/uk/web/css/display/index.md
Labels: update

#1197 update(JS): web/javascript/reference/global_objects/object/entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: update

#1198 update(JS): web/javascript/reference/global_objects/object/keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: update

#1199 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: update

#1153 update(JS): web/javascript/reference/global_objects/number
  files/uk/web/javascript/reference/global_objects/number/index.md
Labels: update

#1202 update(JS): web/javascript/reference/global_objects/json/parse
  files/uk/web/javascript/reference/global_objects/json/parse/index.md
Labels: update

#1203 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
Labels: update

#1204 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#1205 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#1207 update(JS): web/javascript/reference/global_objects/math/round
  files/uk/web/javascript/reference/global_objects/math/round/index.md
Labels: update

#1206 update(JS): web/javascript/reference/global_objects/date/parse
  files/uk/web/javascript/reference/global_objects/date/parse/index.md
Labels: update

#1209 update(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
Labels: update

#1211 update(JS): web/javascript/reference/global_objects/math/max
  files/uk/web/javascript/reference/global_objects/math/max/index.md
Labels: update

#1212 update(JS): web/javascript/reference/global_objects/math/floor
  files/uk/web/javascript/reference/global_objects/math/floor/index.md
Labels: update

#1065 update(JS): web/javascript/reference/global_objects/encodeuricomponent
  files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
Labels: translation, update

#1142 update(CSS): web/css/_colon_nth-child
  files/uk/web/css/_colon_nth-child/index.md
Labels: translation, update

#1223 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#1224 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: update

#1225 update(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
Labels: update

#1046 translation(JS): web/javascript/reference/global_objects/bigint
  files/uk/web/javascript/reference/global_objects/bigint/index.md
  uk_spelling_additions.txt
Labels: translation

#1066 update(JS): web/javascript/guide/using_promises
  files/uk/web/javascript/guide/using_promises/index.md
  uk_ignore_additions.txt
  uk_spelling_additions.txt
Labels: translation, update

#1226 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: update

#1230 update(HTML): web/html
  files/uk/web/html/index.md
Labels: update

#1231 update(JS): web/javascript/reference/global_objects/array/find
  files/uk/web/javascript/reference/global_objects/array/find/index.md
Labels: update

#1232 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#1233 update(HTML): web/html/element
  files/uk/web/html/element/index.md
Labels: update

#1234 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#1237 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: update

#1239 update(CSS): web/css/box-shadow
  files/uk/web/css/box-shadow/index.md
Labels: update

#1241 update(Glossary): glossary
  files/uk/glossary/index.md
Labels: update

#1242 update(HTML): web/html/element/input/date
  files/uk/web/html/element/input/date/index.md
Labels: update

#1243 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: update

#1244 update(HTML): web/html/element/p
  files/uk/web/html/element/p/index.md
Labels: update

#1245 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: update

#1246 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#1247 update(HTML): web/html/element/select
  files/uk/web/html/element/select/index.md
Labels: update

#1248 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: update

#1249 update(HTML): web/html/element/br
  files/uk/web/html/element/br/index.md
Labels: update

#1250 update(HTML): web/html/element/input/number
  files/uk/web/html/element/input/number/index.md
Labels: update

#1251 update(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
Labels: update

#1252 update(HTML): web/html/element/div
  files/uk/web/html/element/div/index.md
Labels: update

#1253 update(HTML): web/html/viewport_meta_tag
  files/uk/web/html/viewport_meta_tag/index.md
Labels: update

#1254 update(HTML): web/html/element/label
  files/uk/web/html/element/label/index.md
Labels: update

#1258 update(JS): web/javascript/reference/global_objects/array/reduce
  files/uk/web/javascript/reference/global_objects/array/reduce/index.md
Labels: update

#1259 update(CSS): web/css/text-decoration
  files/uk/web/css/text-decoration/index.md
Labels: update

#1260 update(CSS): web/css/calc
  files/uk/web/css/calc/index.md
Labels: update

#1261 update(CSS): web/css/css_backgrounds_and_borders/resizing_background_images
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/index.md
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/scaled_mdn_logo.png
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/stretched_firefox_logo.png
Labels: update

#1262 update(JS): web/javascript/closures
  files/uk/web/javascript/closures/index.md
Labels: update

#1227 translation(JS): web/javascript/enumerability_and_ownership_of_properties
  files/uk/web/javascript/enumerability_and_ownership_of_properties/index.md
  uk_spelling_additions.txt
Labels: translation

#1097 update(JS): web/javascript/guide/regular_expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
  uk_spelling_additions.txt
Labels: update

#1161 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update

#1171 update(HTML): web/html/element/script
  files/uk/web/html/element/script/index.md
Labels: translation, update

#1159 update(JS): web/javascript/reference/global_objects/map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: translation, update

#1160 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update

#1167 update(CSS): web/css/overflow
  files/uk/web/css/overflow/index.md
  uk_spelling_additions.txt
Labels: translation, update

#1191 update(JS): web/javascript/reference/global_objects/object/values
  files/uk/web/javascript/reference/global_objects/object/values/index.md
Labels: translation, update

#1200 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
  uk_spelling_additions.txt
Labels: translation, update

#1201 update(JS): web/javascript/reference/statements
  files/uk/web/javascript/reference/statements/index.md
Labels: translation, update

#1208 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: translation, update

#1215 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: translation, update

#1266 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: update

#1236 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: translation, update

#1238 update(JS): web/javascript/reference/statements/import
  files/uk/web/javascript/reference/statements/import/index.md
Labels: translation, update

#1240 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: translation, update

#1255 update(JS): web/javascript/reference/global_objects/string/includes
  files/uk/web/javascript/reference/global_objects/string/includes/index.md
Labels: translation, update

#1267 update(JS): web/javascript/reference/global_objects/object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: translation, update

#1157 translation(JS): Web/JavaScript/Reference/Global_Objects/Object/toString
  files/uk/web/javascript/reference/global_objects/object/tostring/index.md
Labels: translation

#1163 translation(JS): Web/JavaScript/Reference/Global_Objects/Object/defineProperty
  files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
  uk_spelling_additions.txt
Labels: translation

#1172 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
  uk_ignore_additions.txt
  uk_spelling_additions.txt
Labels: translation, update

#890 translation(JS): web/javascript/reference/operators/delete
  files/uk/web/javascript/reference/operators/delete/index.md
  uk_spelling_additions.txt
Labels: translation
