Repository webdoky/content, pull requests merged in 2023-11, with the labels that each got.

#2444 translation(CSS): web/css/_colon_required
  files/uk/web/css/_colon_required/index.md
Labels: translation

#1775 translation(JS): web/javascript/reference/regular_expressions/backreference
  files/uk/web/javascript/reference/regular_expressions/backreference/index.md
  uk_spelling_additions.txt
Labels: translation

#2400 translation(CSS): web/css/font
  files/uk/web/css/font/index.md
Labels: translation

#2397 translation(CSS): web/css/_colon_out-of-range
  files/uk/web/css/_colon_out-of-range/index.md
Labels: translation

#2379 translation(JS): web/javascript/reference/errors
  files/uk/web/javascript/reference/errors/index.md
Labels: translation

#2399 translation(HTML): web/html/element/script/type
  files/uk/web/html/element/script/type/index.md
Labels: translation

#2398 translation(HTML): web/html/element/script/type/speculationrules
  files/uk/web/html/element/script/type/speculationrules/index.md
  uk_spelling_additions.txt
Labels: translation

#2380 translation(JS): web/javascript/reference/functions
  files/uk/web/javascript/reference/functions/index.md
  uk_spelling_additions.txt
Labels: translation

#2368 translation(JS): web/javascript/reference/operators/logical_and
  files/uk/web/javascript/reference/operators/logical_and/index.md
  uk_spelling_additions.txt
Labels: translation

#1739 translation(HTML): web/html/element/audio
  files/uk/web/html/element/audio/index.md
  uk_spelling_additions.txt
Labels: translation

#1783 translation(JS): web/javascript/reference/regular_expressions/capturing_group
  files/uk/web/javascript/reference/regular_expressions/capturing_group/index.md
  uk_spelling_additions.txt
Labels: translation

#2454 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: update

#2457 update(HTML): web/html/viewport_meta_tag
  files/uk/web/html/viewport_meta_tag/index.md
Labels: update

#2453 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update

#1750 translation(glossary): glossary/baseline/compatibility
  files/uk/glossary/baseline/compatibility/index.md
Labels: translation

#2459 update(JS): web/javascript/reference/global_objects/date/tolocaledatestring
  files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
Labels: update

#2460 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#2461 update(JS): web/javascript/reference/global_objects/string/indexof
  files/uk/web/javascript/reference/global_objects/string/indexof/index.md
Labels: update

#2462 update(JS): web/javascript/reference/global_objects/string/slice
  files/uk/web/javascript/reference/global_objects/string/slice/index.md
Labels: update

#2455 update(CSS): web/css/width
  files/uk/web/css/width/index.md
Labels: translation, update

#2456 update(CSS): web/css/css_text/wrapping_breaking_text
  files/uk/web/css/css_text/wrapping_breaking_text/index.md
Labels: translation, update

#2378 translation(HTML): web/html/attributes
  files/uk/web/html/attributes/index.md
  uk_spelling_additions.txt
Labels: translation

#2376 translation(CSS): web/css/gradient
  files/uk/web/css/gradient/index.md
Labels: translation

#2375 translation(CSS): web/css/css_transitions
  files/uk/web/css/css_transitions/index.md
Labels: translation

#2374 translation(CSS): web/css/css_text
  files/uk/web/css/css_text/index.md
Labels: translation

#2372 translation(CSS): web/css/css_box_model
  files/uk/web/css/css_box_model/index.md
Labels: translation

#2370 translation(CSS): web/css/css_animations
  files/uk/web/css/css_animations/index.md
Labels: translation

#2371 translation(CSS): web/css/css_backgrounds_and_borders
  files/uk/web/css/css_backgrounds_and_borders/index.md
Labels: translation

#2458 translation(glossary): glossary/baseline
  files/uk/glossary/baseline/index.md
Labels: translation

#2362 translation(glossary): glossary/snake_case
  files/uk/glossary/snake_case/index.md
Labels: translation

#2355 translation(CSS): web/css/_colon_in-range
  files/uk/web/css/_colon_in-range/index.md
Labels: translation

#1745 translation(HTML): web/html/element/datalist
  files/uk/web/html/element/datalist/index.md
Labels: translation

#2463 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
  uk_spelling_additions.txt
Labels: translation, update

#2377 translation(CSS): web/css/transform-function
  files/uk/web/css/transform-function/coord_in_r2.png
  files/uk/web/css/transform-function/index.md
Labels: translation

#2373 translation(CSS): web/css/css_media_queries
  files/uk/web/css/css_media_queries/index.md
  files/uk/web/css/css_media_queries/media-queries.svg
Labels: translation

#2369 translation(CSS): web/css/@media
  files/uk/web/css/@media/index.md
Labels: translation

#2366 translation(CSS): web/css/flex-grow
  files/uk/web/css/flex-grow/index.md
  uk_spelling_additions.txt
Labels: translation

#2365 translation(glossary): glossary/base64
  files/uk/glossary/base64/index.md
Labels: translation

#2363 translation(guide): web/guide
  files/uk/web/guide/index.md
  uk_spelling_additions.txt
Labels: translation

#2349 translation(CSS): web/css/_colon_indeterminate
  files/uk/web/css/_colon_indeterminate/index.md
Labels: translation

#2020 translation(SVG): web/svg/attribute/decoding
  files/uk/web/svg/attribute/decoding/index.md
Labels: translation

#2019 translation(CSS): web/css/_colon_placeholder-shown
  files/uk/web/css/_colon_placeholder-shown/index.md
Labels: translation

#2465 update(JS): web/javascript/closures
  files/uk/web/javascript/closures/index.md
Labels: update

#2466 update(JS): web/javascript/inheritance_and_the_prototype_chain
  files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
Labels: update

#2467 update(JS): web/javascript/reference/lexical_grammar
  files/uk/web/javascript/reference/lexical_grammar/index.md
Labels: update

#2468 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#2470 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#2471 update(JS): web/javascript/reference/operators/delete
  files/uk/web/javascript/reference/operators/delete/index.md
Labels: update

#2473 update(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
Labels: update

#1823 translation(JS): web/javascript/reference/regular_expressions/character_class_escape
  files/uk/web/javascript/reference/regular_expressions/character_class_escape/index.md
  uk_spelling_additions.txt
Labels: translation

#1845 update(JS): web/javascript/reference/global_objects/array/join
  files/uk/web/javascript/reference/global_objects/array/join/index.md
Labels: translation, update

#1768 translation(CSS): web/css/at-rule
  files/uk/web/css/at-rule/index.md
Labels: translation

#2469 update(JS): web/javascript/reference/global_objects/object/entries
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: translation, update

#2472 update(JS): web/javascript/reference/global_objects/object/values
  files/uk/web/javascript/reference/global_objects/object/values/index.md
Labels: translation, update

#2474 update(JS): web/javascript/reference/global_objects/object/keys
  files/uk/web/javascript/reference/global_objects/object/keys/index.md
Labels: translation, update

#2475 translation(glossary): glossary/internationalization
  files/uk/glossary/internationalization/index.md
Labels: translation

#2476 translation(CSS): web/css/_colon_optional
  files/uk/web/css/_colon_optional/index.md
Labels: translation

#2464 translation(HTML): web/html/element/object
  files/uk/web/html/element/object/index.md
Labels: translation

#2351 translation(CSS): web/css/font-synthesis-position
  files/uk/web/css/font-synthesis-position/index.md
Labels: translation

#2477 fix(HTML): fix live samples in web/html/element/input/button
  files/uk/web/html/element/input/button/index.md
Labels: bug

#2478 fix(HTML): fix live samples in web/html/element/input/color
  files/uk/web/html/element/input/color/index.md
Labels: bug

#2479 fix(HTML): fix live samples in web/html/element/input/month
  files/uk/web/html/element/input/month/index.md
Labels: bug

#2480 fix(HTML): filx live samples in web/html/element/input/range
  files/uk/web/html/element/input/range/index.md
Labels: bug

#1849 update(JS): web/javascript/reference/global_objects/map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: translation, update

#1889 update(JS): web/javascript/reference/global_objects/string/codepointat
  files/uk/web/javascript/reference/global_objects/string/codepointat/index.md
Labels: translation, update

#1809 translation(JS): web/javascript/reference/regular_expressions/character_class
  files/uk/web/javascript/reference/regular_expressions/character_class/index.md
Labels: translation

#2488 update(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
Labels: update

#2491 update(CSS): web/css/align-items
  files/uk/web/css/align-items/index.md
Labels: update

#2492 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: update

#2490 update(JS): web/javascript/reference/statements/switch
  files/uk/web/javascript/reference/statements/switch/index.md
  uk_spelling_additions.txt
Labels: update

#2494 update(JS): web/javascript/reference/global_objects/string/tosource
  files/uk/web/javascript/reference/global_objects/string/tosource/index.md
Labels: update

#1769 translation(HTML): web/html/attributes/readonly
  files/uk/web/html/attributes/readonly/index.md
Labels: translation

#2495 update(CSS): web/css/length
  files/uk/web/css/length/index.md
Labels: update

#2489 update(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/difference/diagram.svg
  files/uk/web/javascript/reference/global_objects/set/index.md
  files/uk/web/javascript/reference/global_objects/set/intersection/diagram.svg
  files/uk/web/javascript/reference/global_objects/set/isdisjointfrom/diagram.svg
  files/uk/web/javascript/reference/global_objects/set/issubsetof/diagram.svg
  files/uk/web/javascript/reference/global_objects/set/issupersetof/diagram.svg
  files/uk/web/javascript/reference/global_objects/set/symmetricdifference/diagram.svg
  files/uk/web/javascript/reference/global_objects/set/union/diagram.svg
Labels: translation, update

#2493 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: translation, update

#2496 update(JS): web/javascript/inheritance_and_the_prototype_chain
  files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
Labels: translation, update

#2498 translation(JSONdata): L10n-common
  files/jsondata/L10n-Common.json
Labels: translation

#2500 feat: size-label-action
  .github/workflows/size-label.yml
Labels: enhancement

#2505 update(JS): web/javascript/language_overview
  files/uk/web/javascript/language_overview/index.md
Labels: update, size/XS

#1996 translation(JS): web/javascript/guide/using_classes
  files/uk/web/javascript/guide/using_classes/figure8.1.png
  files/uk/web/javascript/guide/using_classes/index.md
  uk_spelling_additions.txt
Labels: translation, size/XL

#1828 translation(HTML): web/html/global_attributes/enterkeyhint
  files/uk/web/html/global_attributes/enterkeyhint/index.md
Labels: translation, size/M

#2508 update(CSS): web/css/-moz-image-rect
  files/uk/web/css/-moz-image-rect/index.md
Labels: update, size/XS

#2509 update(CSS): web/css/-moz-force-broken-image-icon
  files/uk/web/css/-moz-force-broken-image-icon/index.md
Labels: update, size/XS

#2510 update(CSS): web/css/-moz-image-region
  files/uk/web/css/-moz-image-region/index.md
Labels: update, size/XS

#2512 update(CSS): web/css/css_backgrounds_and_borders
  files/uk/web/css/css_backgrounds_and_borders/index.md
Labels: update, size/XS

#2514 update(HTML): web/html/element/script/type/speculationrules
  files/uk/web/html/element/script/type/speculationrules/index.md
Labels: update, size/S

#2515 update(JS): web/javascript/reference/iteration_protocols
  files/uk/web/javascript/reference/iteration_protocols/index.md
Labels: update

#2516 update(JS): web/javascript/reference/operators/object_initializer
  files/uk/web/javascript/reference/operators/object_initializer/index.md
Labels: update, size/XS

#2517 update(JS): web/javascript/reference/operators/this
  files/uk/web/javascript/reference/operators/this/index.md
Labels: update, size/XS

#2518 update(JS): web/javascript/reference/global_objects/string/lastindexof
  files/uk/web/javascript/reference/global_objects/string/lastindexof/index.md
Labels: update, size/XS

#2519 update(JS): web/javascript/reference/global_objects/proxy
  files/uk/web/javascript/reference/global_objects/proxy/index.md
Labels: update, size/XS

#2521 update(glossary): glossary/internationalization
  files/uk/glossary/internationalization/index.md
Labels: update, size/XS

#2524 update(CSS): web/css/css_transitions
  files/uk/web/css/css_transitions/index.md
Labels: update, size/XXS

#2528 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: translation, update, size/S

#2527 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update, size/S

#2506 feat: spellcheck action
  .github/workflows/spellcheck.yml
  pass.sh
  scripts/create-file-mapping.js
  scripts/create-message.js
Labels: enhancement, translation, update, size/XS

#2530 Feature: contextual comments
  .github/workflows/spellcheck.yml
  scripts/send-comments.js
Labels: enhancement, translation, update, size/XS

#2531 feat: assign reviewers workflow
  CODEOWNERS
Labels: enhancement

#2533 feat: auto-author-assign
  .github/workflows/auto-author-assign.yml
Labels: enhancement

#2538 update(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
Labels: update

#2537 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update, size/S

#2547 feat: automatic PR title & body
  .github/pull_request_template.md
  .github/workflows/spellcheck.yml
  .github/workflows/translation.yml
  disabled_rules.txt
Labels: enhancement, translation, update, size/XS

#2523 update(CSS): web/css/css_animations/using_css_animations
  files/uk/web/css/css_animations/using_css_animations/index.md
Labels: translation, update, size/M

#2548 feat: PR actuality check
  .github/workflows/pr-actuality-check.yml
Labels: enhancement, translation, size/XS

#2551 update(CSS): web/css/css_selectors
  files/uk/web/css/css_selectors/index.md
Labels: update

#2563 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: update, size/M

#2567 update(JS): web/javascript/reference/global_objects/string/indexof
  files/uk/web/javascript/reference/global_objects/string/indexof/index.md
Labels: translation, update, size/S

#2566 update(JS): web/javascript/guide/regular_expressions
  files/uk/web/javascript/guide/regular_expressions/index.md
Labels: translation, update, size/XS
