Repository webdoky/content, pull requests merged in 2023-08, with the labels that each got.

#1815 update(JS): web/javascript/reference/statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
Labels: translation, update

#1800 update(JS): web/javascript/reference/statements/try...catch
  files/uk/web/javascript/reference/statements/try...catch/index.md
Labels: translation, update

#1975 translation(CSS): web/css/_colon_disabled
  files/uk/web/css/_colon_disabled/index.md
Labels: translation

#1819 update(JS): web/javascript/reference/global_objects/date/now
  files/uk/web/javascript/reference/global_objects/date/now/index.md
Labels: translation, update

#1885 update(JS): web/javascript/reference/global_objects/string/charcodeat
  files/uk/web/javascript/reference/global_objects/string/charcodeat/index.md
  uk_spelling_additions.txt
Labels: translation, update

#1983 translation(JS): web/javascript/reference/global_objects/infinity
  files/uk/web/javascript/reference/global_objects/infinity/index.md
Labels: translation

#1493 translation(JS): web/javascript/reference/statements/if...else
  files/uk/web/javascript/reference/statements/if...else/index.md
Labels: translation

#1502 translation(JS): web/javascript/reference/operators/object_initializer
  files/uk/web/javascript/reference/operators/object_initializer/index.md
  uk_spelling_additions.txt
Labels: translation

#1977 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: translation, update

#1946 update(CSS): web/css/css_selectors
  files/uk/web/css/css_selectors/index.md
Labels: translation, update

#1987 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: translation, update

#1988 update(CSS): web/css/position
  files/uk/web/css/position/index.md
Labels: translation, update

#1980 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: translation, update

#1569 update(JS): web/javascript/reference/global_objects/bigint
  files/uk/web/javascript/reference/global_objects/bigint/index.md
Labels: translation, update

#1709 update(JS): web/javascript/reference/global_objects/intl/numberformat
  files/uk/web/javascript/reference/global_objects/intl/numberformat/index.md
Labels: translation, update

#1992 translation(glossary): glossary/repaint
  files/uk/glossary/repaint/index.md
Labels: translation

#1698 update(CSS): web/css/color
  files/uk/web/css/color/index.md
Labels: translation, update

#1597 translation(HTML): web/html/element/input/range
  files/uk/web/html/element/input/range/index.md
  uk_spelling_additions.txt
Labels: translation

#1676 update(JS): web/javascript/reference/global_objects/encodeuricomponent
  files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
Labels: translation, update

#1953 update(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/index.md
  uk_spelling_additions.txt
Labels: translation, update

#1803 update(JS): web/javascript/reference/global_objects/date/date
  files/uk/web/javascript/reference/global_objects/date/date/index.md
Labels: translation, update

#1995 translation(js): web/javascript/reference/operators/property_accessors
  files/uk/web/javascript/reference/operators/property_accessors/index.md
Labels: translation

#1712 update(CSS): web/css/reference
  files/uk/web/css/reference/index.md
Labels: translation, update

#1539 update(HTML): web/html/global_attributes
  files/uk/web/html/global_attributes/index.md
Labels: translation, update

#1952 update(JS): web/javascript/reference/global_objects/math/log1p
  files/uk/web/javascript/reference/global_objects/math/log1p/index.md
Labels: translation, update

#1559 update(JS): web/javascript/reference/global_objects/math/fround
  files/uk/web/javascript/reference/global_objects/math/fround/index.md
Labels: translation, update

#1554 update(JS): web/javascript/reference/global_objects/math/sqrt
  files/uk/web/javascript/reference/global_objects/math/sqrt/index.md
Labels: translation, update

#1562 update(JS): web/javascript/reference/global_objects/regexp/test
  files/uk/web/javascript/reference/global_objects/regexp/test/index.md
Labels: translation, update

#1710 update(JS): web/javascript/reference/global_objects/string/concat
  files/uk/web/javascript/reference/global_objects/string/concat/index.md
Labels: translation, update

#1711 update(JS): web/javascript/reference/global_objects/string/fromcodepoint
  files/uk/web/javascript/reference/global_objects/string/fromcodepoint/index.md
Labels: translation, update

#1706 update(JS): web/javascript/reference/global_objects/symbol
  files/uk/web/javascript/reference/global_objects/symbol/index.md
Labels: translation, update

#1565 update(JS): web/javascript/reference/global_objects/string/matchall
  files/uk/web/javascript/reference/global_objects/string/matchall/index.md
Labels: translation, update

#1737 translation(HTML): web/html/element/input/url
  files/uk/web/html/element/input/url/index.md
  uk_ignore_additions.txt
  uk_spelling_additions.txt
Labels: translation

#1586 translation(HTML): web/html/element/input/email
  files/uk/web/html/element/input/email/email-pattern-match-bad.png
  files/uk/web/html/element/input/email/enter-valid-email-address.png
  files/uk/web/html/element/input/email/index.md
Labels: translation

#2016 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: update

#2002 update(JS): web/javascript/reference/global_objects/object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: translation, update

#1772 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update

#1998 update(JS): web/javascript/reference/global_objects/math/max
  files/uk/web/javascript/reference/global_objects/math/max/index.md
Labels: update

#2000 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: update

#2012 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
Labels: update

#2013 update(JS): web/javascript/reference/global_objects/math/min
  files/uk/web/javascript/reference/global_objects/math/min/index.md
Labels: update

#1989 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: update

#1981 update(CSS): web/css/align-items
  files/uk/web/css/align-items/index.md
Labels: update

#1978 update(HTML): web/html/element/heading_elements
  files/uk/web/html/element/heading_elements/index.md
Labels: update

#1979 update(HTML): web/html/element/textarea
  files/uk/web/html/element/textarea/index.md
Labels: update

#1976 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: update

#2070 update(JS): web/javascript/reference/global_objects/regexp/test
  files/uk/web/javascript/reference/global_objects/regexp/test/index.md
Labels: update

#2069 update(JS): web/javascript/reference/global_objects/string/trimend
  files/uk/web/javascript/reference/global_objects/string/trimend/index.md
Labels: update

#2108 update(HTML): web/html/content_categories
  files/uk/web/html/content_categories/index.md
Labels: update

#2106 update(CSS): web/css/used_value
  files/uk/web/css/used_value/index.md
Labels: update

#2105 update(CSS): web/css/shorthand_properties
  files/uk/web/css/shorthand_properties/index.md
Labels: update

#2104 update(CSS): web/css/replaced_element
  files/uk/web/css/replaced_element/index.md
Labels: bug, update

#2103 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#2102 update(CSS): web/css/number
  files/uk/web/css/number/index.md
Labels: update

#2004 update(JS): web/javascript/guide/indexed_collections
  files/uk/web/javascript/guide/indexed_collections/index.md
Labels: translation, update

#2033 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: translation, update

#2086 update(CSS): web/css/_colon_not
  files/uk/web/css/_colon_not/index.md
Labels: bug, translation, update

#2040 update(HTML): web/html/element/heading_elements
  files/uk/web/html/element/heading_elements/index.md
Labels: translation, update

#2010 update(JS): web/javascript/reference/statements/import
  files/uk/web/javascript/reference/statements/import/index.md
Labels: translation, update

#2076 update(glossary): glossary/falsy
  files/uk/glossary/falsy/index.md
Labels: translation, update

#2101 update(CSS): web/css/css_media_queries/using_media_queries
  files/uk/web/css/css_media_queries/using_media_queries/index.md
Labels: update

#1567 update(JS): web/javascript/reference/global_objects/typeerror
  files/uk/web/javascript/reference/global_objects/typeerror/index.md
Labels: translation, update

#1564 update(JS): web/javascript/reference/global_objects/string/endswith
  files/uk/web/javascript/reference/global_objects/string/endswith/index.md
Labels: translation, update

#1808 translation(HTML): web/html/attributes/step
  files/uk/web/html/attributes/step/index.md
  uk_spelling_additions.txt
Labels: translation

#2100 update(CSS): web/css/margin
  files/uk/web/css/margin/index.md
Labels: update

#2110 update(HTML): web/html/element/span
  files/uk/web/html/element/span/index.md
Labels: update

#2111 update(HTML): web/html/global_attributes/class
  files/uk/web/html/global_attributes/class/index.md
Labels: update

#2112 update(HTML): web/html/viewport_meta_tag
  files/uk/web/html/viewport_meta_tag/index.md
Labels: update

#2113 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#2114 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: update

#2116 update(JS): web/javascript/inheritance_and_the_prototype_chain
  files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
Labels: update

#2125 update(CSS): web/css/overflow
  files/uk/web/css/overflow/index.md
Labels: update

#2126 update(JS): web/javascript/reference/global_objects/math/pow
  files/uk/web/javascript/reference/global_objects/math/pow/index.md
Labels: update

#2127 update(JS): web/javascript/reference/statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
Labels: update

#2128 update(JS): web/javascript/reference/operators/conditional_operator
  files/uk/web/javascript/reference/operators/conditional_operator/index.md
Labels: update

#2122 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: update

#2119 update(JS): web/javascript/reference/global_objects/array/pop
  files/uk/web/javascript/reference/global_objects/array/pop/index.md
Labels: update

#2120 update(JS): web/javascript/reference/global_objects/array/unshift
  files/uk/web/javascript/reference/global_objects/array/unshift/index.md
Labels: update

#1322 translation(JS): web/javascript/guide/expressions_and_operators
  files/uk/web/javascript/guide/expressions_and_operators/index.md
  uk_spelling_additions.txt
Labels: translation

#2109 update(HTML): web/html/element/hr
  files/uk/web/html/element/hr/index.md
Labels: translation, update

#2117 update(JS): web/javascript/language_overview
  files/uk/web/javascript/language_overview/index.md
  uk_spelling_additions.txt
Labels: update

#2129 update(JS): web/javascript/reference/global_objects/number
  files/uk/web/javascript/reference/global_objects/number/index.md
Labels: update

#2166 update(JS): web/javascript/reference/global_objects/string/raw
  files/uk/web/javascript/reference/global_objects/string/raw/index.md
Labels: update

#2163 update(JS): web/javascript/reference/global_objects/string/fromcodepoint
  files/uk/web/javascript/reference/global_objects/string/fromcodepoint/index.md
Labels: update

#2162 update(JS): web/javascript/reference/global_objects/string/fromcharcode
  files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
Labels: update

#2158 update(JS): web/javascript/reference/global_objects/string/charat
  files/uk/web/javascript/reference/global_objects/string/charat/index.md
  uk_spelling_additions.txt
Labels: update

#2157 update(JS): web/javascript/reference/global_objects/string/bold
  files/uk/web/javascript/reference/global_objects/string/bold/index.md
Labels: update

#2153 update(JS): web/javascript/reference/global_objects/symbol
  files/uk/web/javascript/reference/global_objects/symbol/index.md
Labels: update

#2021 update(JS): web/javascript/reference/global_objects/array/sort
  files/uk/web/javascript/reference/global_objects/array/sort/index.md
Labels: update

#2165 update(JS): web/javascript/reference/global_objects/string/link
  files/uk/web/javascript/reference/global_objects/string/link/index.md
Labels: translation, update

#2164 update(JS): web/javascript/reference/global_objects/string/italics
  files/uk/web/javascript/reference/global_objects/string/italics/index.md
Labels: translation, update

#2161 update(JS): web/javascript/reference/global_objects/string/fontsize
  files/uk/web/javascript/reference/global_objects/string/fontsize/index.md
Labels: translation, update

#2160 update(JS): web/javascript/reference/global_objects/string/fontcolor
  files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
Labels: translation, update

#2159 update(JS): web/javascript/reference/global_objects/string/fixed
  files/uk/web/javascript/reference/global_objects/string/fixed/index.md
Labels: translation, update

#2156 update(JS): web/javascript/reference/global_objects/string/big
  files/uk/web/javascript/reference/global_objects/string/big/index.md
Labels: translation, update

#2154 update(JS): web/javascript/reference/global_objects/string/@@iterator
  files/uk/web/javascript/reference/global_objects/string/@@iterator/index.md
Labels: translation, update

#2152 update(JS): web/javascript/reference/global_objects/regexp/test
  files/uk/web/javascript/reference/global_objects/regexp/test/index.md
Labels: update

#2151 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
  uk_spelling_additions.txt
Labels: update

#1496 translation(JS): web/javascript/reference/statements/const
  files/uk/web/javascript/reference/statements/const/index.md
  uk_spelling_additions.txt
Labels: translation

#1547 update(JS): web/javascript/reference/global_objects/string/length
  files/uk/web/javascript/reference/global_objects/string/length/index.md
  uk_ignore_additions.txt
Labels: translation, update

#1561 update(JS): web/javascript/reference/global_objects/regexp/exec
  files/uk/web/javascript/reference/global_objects/regexp/exec/index.md
Labels: translation, update

#1568 update(JS): web/javascript/reference/iteration_protocols
  files/uk/web/javascript/reference/iteration_protocols/index.md
Labels: translation, update

#1729 update(JS): web/javascript/reference/global_objects/math/imul
  files/uk/web/javascript/reference/global_objects/math/imul/index.md
Labels: translation, update
