Repository webdoky/content, pull requests merged in 2023-03, with the labels that each got.

#1357 update(JS): web/javascript/reference/classes
  files/uk/web/javascript/reference/classes/index.md
Labels: update

#1358 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: update

#1362 update(JS): web/javascript/reference/statements/import
  files/uk/web/javascript/reference/statements/import/index.md
Labels: update

#1363 update(CSS): web/css/using_css_custom_properties
  files/uk/web/css/using_css_custom_properties/index.md
Labels: update

#1364 update(CSS): web/css/background-image
  files/uk/web/css/background-image/index.md
Labels: update

#1365 update(CSS): web/css/box-shadow
  files/uk/web/css/box-shadow/index.md
Labels: update

#1367 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: update

#1368 update(JS): web/javascript/reference/global_objects/array/indexof
  files/uk/web/javascript/reference/global_objects/array/indexof/index.md
Labels: update

#1370 update(JS): web/javascript/reference/global_objects/json/parse
  files/uk/web/javascript/reference/global_objects/json/parse/index.md
Labels: update

#1371 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: update

#1372 update(JS): web/javascript/reference/operators/destructuring_assignment
  files/uk/web/javascript/reference/operators/destructuring_assignment/index.md
Labels: update

#1373 update(JS): web/javascript/reference/operators/typeof
  files/uk/web/javascript/reference/operators/typeof/index.md
Labels: update

#1374 update(Glossary): glossary
  files/uk/glossary/index.md
Labels: update

#1375 update(CSS): web/css/transform-function/translate
  files/uk/web/css/transform-function/translate/index.md
Labels: update

#1376 update(CSS): web/css/justify-content
  files/uk/web/css/justify-content/index.md
Labels: update

#1377 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
Labels: update

#1379 update(CSS): web/css/specificity
  files/uk/web/css/specificity/index.md
Labels: update

#1380 update(HTML): web/html/element/input/date
  files/uk/web/html/element/input/date/index.md
Labels: update

#1378 update(CSS): web/css/background-size
  files/uk/web/css/background-size/index.md
Labels: update

#1381 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: update

#1382 update(HTML): web/html/element/p
  files/uk/web/html/element/p/index.md
Labels: update

#1383 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: update

#1384 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#1385 update(JS): web/javascript/reference/global_objects/array/some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: update

#1386 update(JS): web/javascript/reference/global_objects/array/findindex
  files/uk/web/javascript/reference/global_objects/array/findindex/index.md
Labels: update

#1387 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: update

#1388 update(JS): web/javascript/reference/global_objects/array/concat
  files/uk/web/javascript/reference/global_objects/array/concat/index.md
Labels: update

#1389 update(JS): web/javascript/reference/statements/for...in
  files/uk/web/javascript/reference/statements/for...in/index.md
Labels: update

#1390 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: update

#1391 update(JS): web/javascript/reference/global_objects/array/join
  files/uk/web/javascript/reference/global_objects/array/join/index.md
Labels: update

#1392 update(JS): web/javascript/reference/statements/switch
  files/uk/web/javascript/reference/statements/switch/index.md
Labels: update

#1393 update(JS): web/javascript/reference/global_objects/promise/all
  files/uk/web/javascript/reference/global_objects/promise/all/index.md
Labels: update

#1394 update(JS): web/javascript/reference/global_objects/string/match
  files/uk/web/javascript/reference/global_objects/string/match/index.md
Labels: update

#1395 update(JS): web/javascript/reference/global_objects/parseint
  files/uk/web/javascript/reference/global_objects/parseint/index.md
Labels: update

#1396 update(CSS): web/css/font-weight
  files/uk/web/css/font-weight/index.md
Labels: update

#1397 update(CSS): web/css/grid-template-columns
  files/uk/web/css/grid-template-columns/index.md
Labels: update

#1398 update(CSS): web/css/media_queries/using_media_queries
  files/uk/web/css/media_queries/using_media_queries/index.md
Labels: update

#1399 update(CSS): web/css/:nth-child
  files/uk/web/css/_colon_nth-child/index.md
Labels: update

#1400 update(CSS): web/css/box-sizing
  files/uk/web/css/box-sizing/index.md
Labels: update

#1361 update(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/index.md
Labels: translation, update

#1369 update(JS): web/javascript/reference/global_objects/object
  files/uk/web/javascript/reference/global_objects/object/index.md
Labels: translation, update

#1327 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: translation, update

#1402 update(CSS): web/css/display
  files/uk/web/css/display/index.md
Labels: update

#1311 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: translation, update

#1405 update(JS): web/javascript/reference/statements/async_function
  files/uk/web/javascript/reference/statements/async_function/index.md
Labels: update

#1406 update(CSS): web/css/css_flexible_box_layout/basic_concepts_of_flexbox
  files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
Labels: update

#1408 update(CSS): web/css/overflow
  files/uk/web/css/overflow/index.md
Labels: update

#1410 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: update

#1415 update(JS): web/javascript/reference/global_objects/string/substring
  files/uk/web/javascript/reference/global_objects/string/substring/index.md
Labels: update

#1416 update(JS): web/javascript/reference/operators/nullish_coalescing
  files/uk/web/javascript/reference/operators/nullish_coalescing/index.md
  files/uk/web/javascript/reference/statements/for...of/index.md
Labels: update

#1417 update(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
Labels: update

#1418 update(JS): web/javascript/reference/global_objects/date/now
  files/uk/web/javascript/reference/global_objects/date/now/index.md
Labels: update

#1419 update(JS): web/javascript/reference/global_objects/math
  files/uk/web/javascript/reference/global_objects/math/index.md
Labels: update

#1420 update(JS): web/javascript/reference/global_objects/date/parse
  files/uk/web/javascript/reference/global_objects/date/parse/index.md
Labels: update

#1421 update(JS): web/javascript/reference/global_objects/string/replaceall
  files/uk/web/javascript/reference/global_objects/string/replaceall/index.md
Labels: update

#1422 update(JS): web/javascript/reference/global_objects/array/every
  files/uk/web/javascript/reference/global_objects/array/every/index.md
Labels: update

#1423 update(JS): web/javascript/guide
  files/uk/web/javascript/guide/index.md
Labels: update

#1424 update(JS): web/javascript/data_structures
  files/uk/web/javascript/data_structures/index.md
Labels: update

#1427 update(JS): web/javascript/reference/statements/try...catch
  files/uk/web/javascript/reference/statements/try...catch/index.md
Labels: update

#1429 update(JS): web/javascript/reference/global_objects/array/length
  files/uk/web/javascript/reference/global_objects/array/length/index.md
Labels: update

#1432 update(CSS): web/css/transform-function/rotate
  files/uk/web/css/transform-function/rotate/index.md
Labels: update

#1433 update(CSS): web/css/css_transitions/using_css_transitions
  files/uk/web/css/css_transitions/using_css_transitions/index.md
Labels: update

#1435 update(CSS): web/css/border-radius
  files/uk/web/css/border-radius/index.md
Labels: update

#1436 update(CSS): web/css/background-position
  files/uk/web/css/background-position/index.md
Labels: update

#1437 update(CSS): web/css/transform
  files/uk/web/css/transform/index.md
Labels: update

#1313 update(CSS): web/css/css_animations/using_css_animations
  files/uk/web/css/css_animations/using_css_animations/index.md
Labels: update

#1438 update(CSS): web/css/text-overflow
  files/uk/web/css/text-overflow/index.md
Labels: update

#1440 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: update

#1441 update(CSS): web/css/text-decoration
  files/uk/web/css/text-decoration/index.md
Labels: update

#1442 update(CSS): web/css/calc
  files/uk/web/css/calc/index.md
Labels: update

#1443 update(CSS): web/css/white-space
  files/uk/web/css/white-space/index.md
Labels: update

#1444 update(CSS): web/css/flex
  files/uk/web/css/flex/index.md
Labels: update

#1445 update(CSS): web/css/background
  files/uk/web/css/background/index.md
Labels: update

#1446 update(CSS): web/css/css_text/wrapping_text
  files/uk/web/css/css_text/wrapping_text/index.md
Labels: update

#1448 update(CSS): web/css/css_grid_layout/basic_concepts_of_grid_layout
  files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
Labels: update

#1449 update(CSS): web/css/css_backgrounds_and_borders/resizing_background_images
  files/uk/web/css/css_backgrounds_and_borders/resizing_background_images/index.md
Labels: update

#1450 update(CSS): web/css/text-transform
  files/uk/web/css/text-transform/index.md
Labels: update

#1411 update(JS): web/javascript/reference/global_objects/set
  files/uk/web/javascript/reference/global_objects/set/index.md
Labels: update

#1451 update(CSS): web/css/backdrop-filter
  files/uk/web/css/backdrop-filter/index.md
Labels: update

#1452 update(CSS): web/css/flex-direction
  files/uk/web/css/flex-direction/index.md
Labels: update

#1453 update(CSS): web/css/line-height
  files/uk/web/css/line-height/index.md
Labels: update

#1455 update(HTML): web/html/element/br
  files/uk/web/html/element/br/index.md
Labels: update

#1456 update(HTML): web/html/element/input/number
  files/uk/web/html/element/input/number/index.md
Labels: update

#1457 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: update

#1458 update(HTML): web/html/element/table
  files/uk/web/html/element/table/index.md
Labels: update

#1459 update(HTML): web/html/element/div
  files/uk/web/html/element/div/index.md
Labels: update

#1460 update(JS): Web/JavaScript/Reference/Statements/import
  files/uk/web/javascript/reference/statements/import/index.md
Labels: bug, update

#1461 update(HTML): web/html/element/script
  files/uk/web/html/element/script/index.md
  uk_spelling_additions.txt
Labels: update

#1462 update(HTML): web/html/viewport_meta_tag
  files/uk/web/html/viewport_meta_tag/index.md
Labels: update

#1463 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: update

#1464 update(JS): web/javascript/reference/global_objects/array/from
  files/uk/web/javascript/reference/global_objects/array/from/index.md
Labels: update

#1466 update(JS): web/javascript/reference/global_objects/string/slice
  files/uk/web/javascript/reference/global_objects/string/slice/index.md
Labels: update

#1465 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#1467 update(JS): web/javascript/reference/global_objects/string/includes
  files/uk/web/javascript/reference/global_objects/string/includes/index.md
Labels: update

#1468 update(JS): web/javascript/reference/global_objects/date/toisostring
  files/uk/web/javascript/reference/global_objects/date/toisostring/index.md
Labels: update

#1469 update(JS): web/javascript/reference/global_objects/array/shift
  files/uk/web/javascript/reference/global_objects/array/shift/index.md
Labels: update

#1470 update(JS): web/javascript/reference/global_objects/array/pop
  files/uk/web/javascript/reference/global_objects/array/pop/index.md
Labels: update

#1471 update(JS): web/javascript/reference/global_objects/math/max
  files/uk/web/javascript/reference/global_objects/math/max/index.md
Labels: update

#1473 update(JS): web/javascript/reference/global_objects/array/flat
  files/uk/web/javascript/reference/global_objects/array/flat/index.md
Labels: update

#1474 update(JS): web/javascript/reference/global_objects/math/floor
  files/uk/web/javascript/reference/global_objects/math/floor/index.md
Labels: update

#1475 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: update

#1476 update(JS): web/javascript/reference/global_objects/array/isarray
  files/uk/web/javascript/reference/global_objects/array/isarray/index.md
Labels: update

#1477 update(JS): web/javascript/closures
  files/uk/web/javascript/closures/index.md
Labels: update

#1478 update(JS): web/javascript/reference/global_objects/date/tolocaledatestring
  files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
Labels: update

#1479 update(JS): web/javascript/reference/global_objects/date/date
  files/uk/web/javascript/reference/global_objects/date/date/index.md
Labels: update

#1483 update(JS): web/javascript/reference/global_objects/object/values
  files/uk/web/javascript/reference/global_objects/object/values/index.md
Labels: update

#1484 update(JS): web/javascript/reference/global_objects/date/tolocalestring
  files/uk/web/javascript/reference/global_objects/date/tolocalestring/index.md
Labels: update

#1485 update(JS): web/javascript/reference/global_objects/promise/resolve
  files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
Labels: update

#1486 update(JS): web/javascript/reference/operators/await
  files/uk/web/javascript/reference/operators/await/index.md
Labels: update

#1487 update(JS): web/javascript/reference/errors/not_defined
  files/uk/web/javascript/reference/errors/not_defined/index.md
Labels: update

#1482 update(JS): web/javascript/reference/global_objects/array/reverse
  files/uk/web/javascript/reference/global_objects/array/reverse/index.md
Labels: update

#1488 update(JS): web/javascript/guide/regular_expressions/cheatsheet
  files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
  uk_spelling_additions.txt
Labels: update

#1489 update(JS): web/javascript/reference/global_objects/intl/numberformat
  files/uk/web/javascript/reference/global_objects/intl/numberformat/index.md
Labels: update

#1229 translation(JS): web/javascript/reference/lexical_grammar
  files/uk/web/javascript/reference/lexical_grammar/index.md
  uk_spelling_additions.txt
Labels: translation

#1256 translation(CSS): web/css/replaced_element
  files/uk/web/css/replaced_element/index.md
  uk_spelling_additions.txt
Labels: translation

#1257 translation(CSS): web/css/image
  files/uk/web/css/image/index.md
Labels: translation

#1265 translation(CSS): web/css/shorthand_properties
  files/uk/web/css/shorthand_properties/border1.png
  files/uk/web/css/shorthand_properties/border2.png
  files/uk/web/css/shorthand_properties/border3.png
  files/uk/web/css/shorthand_properties/border4.png
  files/uk/web/css/shorthand_properties/corner1.png
  files/uk/web/css/shorthand_properties/corner2.png
  files/uk/web/css/shorthand_properties/corner3.png
  files/uk/web/css/shorthand_properties/corner4.png
  files/uk/web/css/shorthand_properties/index.md
Labels: translation

#1268 translation(JS): web/javascript/reference/statements/let
  files/uk/web/javascript/reference/statements/let/index.md
Labels: translation

#1269 translation(JS): web/javascript/reference/global_objects/error
  files/uk/web/javascript/reference/global_objects/error/index.md
Labels: translation

#1270 translation(JS): web/javascript/reference/global_objects/boolean
  files/uk/web/javascript/reference/global_objects/boolean/index.md
  uk_spelling_additions.txt
Labels: translation

#1274 translation(JS): web/javascript/reference/global_objects/object/getownpropertynames
  files/uk/web/javascript/reference/global_objects/object/getownpropertynames/index.md
  uk_spelling_additions.txt
Labels: translation

#1353 update(JS): web/javascript/reference/global_objects/object/entries
  files/uk/web/javascript/reference/global_objects/map/index.md
  files/uk/web/javascript/reference/global_objects/object/entries/index.md
Labels: translation, update

#1138 translation(JS): web/javascript/reference/operators/null
  files/uk/web/javascript/reference/operators/null/index.md
Labels: translation

#1494 update(JS): web/javascript/reference/lexical_grammar
  files/uk/web/javascript/reference/lexical_grammar/index.md
Labels: update

#1495 update(JS): web/javascript/reference/global_objects/object/hasownproperty
  files/uk/web/javascript/reference/global_objects/object/hasownproperty/index.md
Labels: update

#1498 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: update

#1499 update(HTML): web/html/element/input/radio
  files/uk/web/html/element/input/radio/index.md
Labels: update

#1501 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: update

#1503 update(CSS): web/css/color_value
  files/uk/web/css/color_value/index.md
Labels: translation, update

#1505 update(JS): web/javascript/reference/global_objects/string/padstart
  files/uk/web/javascript/reference/global_objects/string/padstart/index.md
Labels: update

#1510 update(CSS): web/css/text-align
  files/uk/web/css/text-align/index.md
Labels: update

#1513 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: update

#1514 update(JS): web/javascript/reference/global_objects/string/charat
  files/uk/web/javascript/reference/global_objects/string/charat/index.md
Labels: update

#1520 update(JS): web/javascript/reference/global_objects/string/touppercase
  files/uk/web/javascript/reference/global_objects/string/touppercase/index.md
Labels: update

#1521 update(CSS): web/css/inheritance
  files/uk/web/css/inheritance/index.md
Labels: update

#1522 update(CSS): web/css/length
  files/uk/web/css/length/index.md
Labels: update

#1524 update(JS): web/javascript/reference/global_objects/string/tolowercase
  files/uk/web/javascript/reference/global_objects/string/tolowercase/index.md
Labels: update

#1412 update(JS): web/javascript/reference/global_objects/string/split
  files/uk/web/javascript/reference/global_objects/string/split/index.md
Labels: translation, update

#1428 update(JS): web/javascript/reference/global_objects/number
  files/uk/web/javascript/reference/global_objects/number/index.md
Labels: translation, update

#1434 update(CSS): web/css/align-items
  files/uk/web/css/align-items/index.md
Labels: translation, update

#1472 update(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
Labels: translation, update

#1526 update(HTML): web/html
  files/uk/web/html/index.md
Labels: update

#1527 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: update

#1530 update(CSS): web/css/height
  files/uk/web/css/height/index.md
Labels: update

#1531 update(CSS): web/css/css_selectors
  files/uk/web/css/css_selectors/index.md
Labels: update

#1532 update(CSS): web/css/z-index
  files/uk/web/css/z-index/index.md
Labels: update

#1534 update(CSS): web/css/flex-wrap
  files/uk/web/css/flex-wrap/index.md
Labels: update

#1535 update(CSS): web/css/-moz-image-rect
  files/uk/web/css/-moz-image-rect/index.md
Labels: update

#1536 update(CSS): web/css/value_definition_syntax
  files/uk/web/css/value_definition_syntax/index.md
Labels: update

#1537 update(CSS): web/css/margin
  files/uk/web/css/margin/index.md
Labels: update
