Repository webdoky/content, pull requests merged in 2024-04, with the labels that each got.

#2933 translation(HTML): web/html/attributes/min
  files/uk/web/html/attributes/min/index.md
Labels: translation, size/M, Criticality: high

#2939 update(Glossary): glossary/deep_copy
  files/uk/glossary/deep_copy/index.md
Labels: translation, update, size/S

#2938 update(Glossary): glossary/shallow_copy
  files/uk/glossary/shallow_copy/index.md
Labels: translation, update, size/S

#2940 update(SVG): web/svg/attribute
  files/uk/web/svg/attribute/index.md
Labels: translation, update, size/XS

#2946 update(HTML): web/html/element/input/tel
  files/uk/web/html/element/input/tel/index.md
Labels: update

#2947 update(HTML): web/html/element/input/email
  files/uk/web/html/element/input/email/index.md
Labels: update

#2944 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: translation, update, size/S, Criticality: high

#2949 update(CSS): web/css/calc
  files/uk/web/css/calc/index.md
Labels: translation, update, size/S, Criticality: mild

#2948 update(HTML): web/html/element/progress
  files/uk/web/html/element/progress/index.md
Labels: translation, update, size/XS, Criticality: zero

#2945 update(HTML): web/html/element/input/range
  files/uk/web/html/element/input/range/index.md
Labels: translation, update, size/S, Criticality: mild

#2937 update(SVG): web/svg
  files/uk/web/svg/index.md
Labels: translation, update, size/XS, Criticality: low

#2936 update(JS): web/javascript/reference/operators/this
  files/uk/web/javascript/reference/operators/this/index.md
Labels: translation, update, size/M, Criticality: zero

#2919 update(HTML): web/html/element/textarea
  files/uk/web/html/element/textarea/index.md
Labels: translation, update, size/S, Criticality: mild

#2908 update(CSS): web/css/css_colors/applying_color
  files/uk/web/css/css_colors/applying_color/index.md
Labels: translation, update, size/S, Criticality: mild

#2907 update(CSS): web/css/css_colors
  files/uk/web/css/css_colors/index.md
Labels: translation, update, size/S, Criticality: zero

#2954 update(CSS): web/css/_colon_enabled
  files/uk/web/css/_colon_enabled/index.md
Labels: update

#2955 update(CSS): web/css/color_value/light-dark
  files/uk/web/css/color_value/light-dark/index.md
Labels: translation, update, size/XS, Criticality: zero

#2953 update(HTML): web/html/element/ol
  files/uk/web/html/element/ol/index.md
Labels: translation, update, size/S, Criticality: zero

#2952 update(CSS): web/css/color
  files/uk/web/css/color/index.md
Labels: translation, update, size/XS, Criticality: low

#2950 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: translation, update, size/S, Criticality: mild

#2915 update(HTML): web/html/attributes/autocomplete
  files/uk/web/html/attributes/autocomplete/index.md
Labels: translation, update, size/L, Criticality: zero

#2880 update(HTML): web/html/element/input/button
  files/uk/web/html/element/input/button/index.md
Labels: translation, update, size/S, Criticality: zero

#2883 update(CSS): web/css/_doublecolon_first-line
  files/uk/web/css/_doublecolon_first-line/index.md
Labels: translation, update, size/S, Criticality: zero

#2887 update(CSS): web/css/color_value
  files/uk/web/css/color_value/index.md
Labels: translation, update, size/S, Criticality: mild

#2888 update(CSS): web/css/@media
  files/uk/web/css/@media/index.md
Labels: translation, update, size/S, Criticality: zero

#2876 update(Glossary): glossary/void_element
  files/uk/glossary/void_element/index.md
Labels: translation, update, size/S, Criticality: low

#2872 update(HTML): web/html/element/form
  files/uk/web/html/element/form/index.md
Labels: translation, update, size/S, Criticality: mild

#2870 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update, size/S, Criticality: mild

#2864 update(CSS): web/css/_colon_disabled
  files/uk/web/css/_colon_disabled/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/S, Criticality: zero

#2862 update(CSS): web/css/background-position
  files/uk/web/css/background-position/index.md
Labels: translation, update, size/S, Criticality: mild

#2885 update(CSS): web/css/white-space
  files/uk/web/css/white-space/index.md
Labels: translation, update, size/S, Criticality: mild

#2901 update(JS): web/javascript/reference/global_objects/json
  files/uk/web/javascript/reference/global_objects/json/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/M, Criticality: zero

#2834 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update, size/S, Criticality: low

#2804 update(JS): web/javascript/reference/global_objects/boolean
  files/uk/web/javascript/reference/global_objects/boolean/index.md
Labels: translation, update, size/S, Criticality: low

#2805 update(JS): web/javascript/guide/grammar_and_types
  files/uk/web/javascript/guide/grammar_and_types/index.md
Labels: translation, update, size/S, Criticality: mild

#2799 update(JS): web/javascript/reference/global_objects/date/parse
  files/uk/web/javascript/reference/global_objects/date/parse/index.md
Labels: translation, update, size/S, Criticality: low

#2781 update(CSS): web/css/length
  files/uk/web/css/length/index.md
Labels: translation, update, size/M, Criticality: low

#2768 update(CSS): web/css/css_media_queries/using_media_queries
  files/uk/web/css/css_media_queries/using_media_queries/index.md
Labels: translation, update, size/M, Criticality: low

#2775 update(CSS): web/css
  files/uk/web/css/index.md
Labels: translation, update, size/S, Criticality: mild

#2767 update(CSS): web/css/css_media_queries
  files/uk/web/css/css_media_queries/index.md
Labels: translation, update, size/M, Criticality: zero

#2762 update(HTML): web/html/element
  files/uk/web/html/element/index.md
Labels: translation, update, size/M, Criticality: mild

#2735 update(CSS): web/css/_colon_indeterminate
  files/uk/web/css/_colon_indeterminate/index.md
Labels: translation, update, size/S, Criticality: zero

#2792 update(JS): web/javascript/reference/global_objects/array/slice
  files/uk/web/javascript/reference/global_objects/array/slice/index.md
Labels: translation, update, size/S, Criticality: mild

#2957 update(HTML): web/html/element/meter
  files/uk/web/html/element/meter/index.md
Labels: translation, update, size/XS

#2802 update(JS): web/javascript/reference/global_objects/string/length
  files/uk/web/javascript/reference/global_objects/string/length/index.md
Labels: translation, update, size/S, Criticality: mild

#2958 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update, size/XS

#2959 translation(HTML): web/html/element/header
  files/uk/web/html/element/header/index.md
  files/uk/web/html/element/header/mdn-logo-sm.png
  uk_spelling_additions.txt
Labels: translation, size/M, Criticality: high

#2962 update(CSS): web/css/white-space
  files/uk/web/css/white-space/index.md
Labels: translation, update, size/XS

#2967 update(HTML): web/html/attributes/autocomplete
  files/uk/web/html/attributes/autocomplete/index.md
Labels: translation, update, size/S

#2963 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: translation, update, size/S, Criticality: high

#2964 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: translation, update, size/S, Criticality: high

#2970 update(CSS): web/css/border-color
  files/uk/web/css/border-color/index.md
Labels: translation, update, size/XS

#2971 update(HTML): web/html
  files/uk/web/html/index.md
Labels: translation, update, size/S

#2973 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: update

#2974 update(CSS): web/css/caret-color
  files/uk/web/css/caret-color/index.md
Labels: update

#2972 update(JS): web/javascript/reference/global_objects/encodeuricomponent
  files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
Labels: translation, update, size/S

#2978 update(HTML): web/html/element/header
  files/uk/web/html/element/header/index.md
Labels: translation, update, size/S

#2977 translation(HTML): web/html/element/article
  .husky/pre-commit
  .lintstagedrc
  .lintstagedrc.json
  .vscode/settings.json
  files/uk/web/html/element/article/index.md
  package.json
  yarn.lock
Labels: translation, size/M, Criticality: mild
