Repository webdoky/content, pull requests merged in 2024-08, with the labels that each got.

#3221 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: translation, update, size/S

#3219 translation(JS): web/javascript/reference/operators/function
  files/uk/web/javascript/reference/operators/function/index.md
Labels: translation, size/M, Criticality: mild

#3214 update(HTML): web/html/element/input/number
  files/uk/web/html/element/input/number/index.md
Labels: translation, update, size/M, Criticality: mild

#3223 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: translation, update, size/S

#3224 update(HTML): web/html/viewport_meta_tag
  files/uk/web/html/viewport_meta_tag/index.md
Labels: translation, update, size/S

#3225 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: translation, update, size/M

#3226 update(JS): web/javascript/reference/global_objects/regexp
  files/uk/web/javascript/reference/global_objects/regexp/index.md
Labels: translation, update, size/S

#3228 update(CSS): web/css/color_value
  files/uk/web/css/color_value/index.md
Labels: translation, update, size/S

#3229 update(CSS): web/css/width
  files/uk/web/css/width/index.md
Labels: translation, update, size/XS

#3230 update(CSS): web/css/height
  files/uk/web/css/height/index.md
Labels: translation, update, size/XS

#3231 update(CSS): web/css/_doublecolon_placeholder
  files/uk/web/css/_doublecolon_placeholder/index.md
Labels: translation, update, size/XS

#3232 update(CSS): web/css/@media
  files/uk/web/css/@media/index.md
Labels: translation, update, size/S

#3233 update(HTML): web/html/element/input/datetime-local
  files/uk/web/html/element/input/datetime-local/index.md
Labels: translation, update, size/M

#3234 update(CSS): web/css/transform-function
  files/uk/web/css/transform-function/index.md
Labels: translation, update, size/S

#3235 update(HTML): web/html/element/heading_elements
  files/uk/web/html/element/heading_elements/index.md
Labels: translation, update, size/S

#3236 update(HTML): web/html/element/li
  files/uk/web/html/element/li/index.md
Labels: translation, update, size/XS

#3237 update(HTML): web/html/element/input/submit
  files/uk/web/html/element/input/submit/index.md
Labels: translation, update, size/S

#3238 update(HTML): web/html/element/audio
  files/uk/web/html/element/audio/index.md
Labels: translation, update, size/S

#3240 update(HTML): web/html/attributes
  files/uk/web/html/attributes/index.md
Labels: translation, update, size/S

#3241 update(JS): web/javascript/reference/operators/logical_and
  files/uk/web/javascript/reference/operators/logical_and/index.md
Labels: translation, update, size/S

#3243 update(JS): web/javascript/reference/operators/delete
  files/uk/web/javascript/reference/operators/delete/index.md
Labels: translation, update, size/S

#3244 update(JS): web/javascript/reference/operators/this
  files/uk/web/javascript/reference/operators/this/index.md
Labels: translation, update, size/S

#3245 update(JS): web/javascript/reference/global_objects/math/pow
  files/uk/web/javascript/reference/global_objects/math/pow/index.md
Labels: update

#3195 update(CSS): web/css/specificity
  files/uk/web/css/specificity/index.md
Labels: translation, update, size/S, Criticality: mild

#3247 translation(JS): web/javascript/reference/global_objects/string/symbol.iterator
  files/uk/web/javascript/reference/global_objects/string/symbol.iterator/index.md
Labels: update

#3248 update(CSS): web/css/color
  files/uk/web/css/color/index.md
Labels: translation, update, size/S

#3249 update(CSS): web/css/length
  files/uk/web/css/length/index.md
Labels: translation, update, size/M

#3251 update(HTML): web/html/element/input/password
  files/uk/web/html/element/input/password/index.md
Labels: translation, update, size/S

#3252 update(HTML): web/html/element/input/color
  files/uk/web/html/element/input/color/index.md
Labels: translation, update, size/S

#3253 update(HTML): web/html/element/header
  files/uk/web/html/element/header/index.md
Labels: translation, update, size/S

#3254 update(HTML): web/html/element/input/hidden
  files/uk/web/html/element/input/hidden/index.md
Labels: translation, update, size/S

#3255 update(HTML): web/html/element/input/month
  files/uk/web/html/element/input/month/index.md
Labels: translation, update, size/S

#3256 update(HTML): web/html/element/input/image
  files/uk/web/html/element/input/image/index.md
Labels: translation, update, size/S

#3257 update(HTML): web/html/element/canvas
  files/uk/web/html/element/canvas/index.md
Labels: translation, update, size/S

#3258 update(JS): web/javascript/reference/global_objects/bigint
  files/uk/web/javascript/reference/global_objects/bigint/index.md
Labels: translation, update, size/S

#3259 update(JS): web/javascript/reference/global_objects/string/charat
  files/uk/web/javascript/reference/global_objects/string/charat/index.md
Labels: translation, update, size/S

#3262 update(JS): web/javascript/reference/global_objects/object/valueof
  files/uk/web/javascript/reference/global_objects/object/valueof/index.md
Labels: translation, update, size/S

#3263 update(Guide): web/guide
  files/uk/web/guide/index.md
Labels: translation, update, size/S

#3264 update(Glossary): glossary/falsy
  files/uk/glossary/falsy/index.md
Labels: translation, update, size/XS

#3265 update(Glossary): glossary/iife
  files/uk/glossary/iife/index.md
Labels: translation, update, size/S

#3266 update(Glossary): glossary/primitive
  files/uk/glossary/primitive/index.md
Labels: translation, update, size/S

#3267 update(Glossary): glossary/request_header
  files/uk/glossary/request_header/index.md
Labels: translation, update, size/S

#3268 update(Glossary): glossary/shallow_copy
  files/uk/glossary/shallow_copy/index.md
Labels: translation, update, size/S

#3269 update(Glossary): glossary/deep_copy
  files/uk/glossary/deep_copy/index.md
Labels: translation, update, size/M

#2704 translation(CSS): web/css/@layer
  files/uk/web/css/@layer/index.md
  uk_spelling_additions.txt
Labels: translation, size/M, Criticality: mild

#3246 update(JS): web/javascript/reference/iteration_protocols
  files/uk/web/javascript/reference/iteration_protocols/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/L

#2996 update(HTML): web/html/element/script
  files/uk/web/html/element/script/async-defer.jpg
  files/uk/web/html/element/script/index.md
Labels: translation, update, size/L, Criticality: low

#3250 update(CSS): web/css/value_definition_syntax
  files/uk/web/css/value_definition_syntax/index.md
Labels: translation, update, size/M, Criticality: low

#3271 update(CSS): web/css/using_css_custom_properties
  files/uk/web/css/using_css_custom_properties/index.md
Labels: translation, update, size/S

#3272 update(CSS): web/css/gradient/linear-gradient
  files/uk/web/css/gradient/linear-gradient/index.md
Labels: translation, update, size/XS

#3154 update(JS): web/javascript/reference/global_objects/boolean
  files/uk/web/javascript/reference/global_objects/boolean/index.md
Labels: translation, update, size/M, Criticality: low

#3186 update(JS): web/javascript/reference/global_objects/string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update, size/M, Criticality: mild

#3222 update(JS): web/javascript/reference/global_objects/array/slice
  files/uk/web/javascript/reference/global_objects/array/slice/index.md
Labels: translation, update, size/S, Criticality: mild

#3046 update(CSS): web/css/calc
  files/uk/web/css/calc/index.md
Labels: translation, update, size/M, Criticality: mild

#3035 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update, size/L, Criticality: mild

#2997 update(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
Labels: translation, update, size/M, Criticality: mild

#3055 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: translation, update, size/L, Criticality: mild

#3242 update(JS): web/javascript/reference/global_objects/promise/then
  files/uk/web/javascript/reference/global_objects/promise/then/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/S, Criticality: mild

#3189 update(CSS): web/css/position
  files/uk/web/css/position/index.md
Labels: translation, update, size/M, Criticality: mild

#3190 update(JS): web/javascript/reference/template_literals
  files/uk/web/javascript/reference/template_literals/index.md
Labels: translation, update, size/S, Criticality: low

#3213 update(CSS): web/css/line-height
  files/uk/web/css/line-height/index.md
Labels: translation, update, size/S, Criticality: mild

#3217 update(JS): web/javascript/reference/global_objects/promise/resolve
  files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
Labels: translation, update, size/S, Criticality: low

#3194 update(CSS): web/css/justify-content
  files/uk/web/css/justify-content/index.md
Labels: translation, update, size/M, Criticality: mild

#3227 update(CSS): web/css/text-align
  files/uk/web/css/text-align/index.md
Labels: translation, update, size/S, Criticality: mild

#3019 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: translation, update, size/M, Criticality: mild

#3108 update(CSS): web/css/flex-basis
  files/uk/web/css/flex-basis/firefox-flex-basis.png
  files/uk/web/css/flex-basis/index.md
Labels: translation, update, size/M, Criticality: low

#3120 update(HTML): web/html/element/input/time
  files/uk/web/html/element/input/time/index.md
Labels: translation, update, size/M, Criticality: low

#3021 update(JS): web/javascript/reference/global_objects/promise
  files/uk/web/javascript/reference/global_objects/promise/index.md
Labels: translation, update, size/M, Criticality: mild

#3201 update(CSS): web/css/vertical-align
  files/uk/web/css/vertical-align/index.md
Labels: translation, update, size/S, Criticality: low

#3156 update(JS): web/javascript/inheritance_and_the_prototype_chain
  files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/M, Criticality: low

#3107 update(CSS): web/css/flex-grow
  files/uk/web/css/flex-grow/index.md
Labels: translation, update, size/M, Criticality: low

#3239 update(HTML): web/html/attributes/autocomplete
  files/uk/web/html/attributes/autocomplete/index.md
Labels: translation, update, size/L, Criticality: low

#3036 update(HTML): web/html/element/iframe
  files/uk/web/html/element/iframe/index.md
Labels: translation, update, size/M, Criticality: low

#3273 translation(CSS): web/css/transform-function/scale
  files/uk/web/css/transform-function/scale/index.md
Labels: translation, size/M, Criticality: mild

#3277 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
Labels: translation, update, size/XS

#3278 update(CSS): web/css/specificity
  files/uk/web/css/specificity/index.md
Labels: translation, update, size/S

#3279 update(CSS): web/css/align-items
  files/uk/web/css/align-items/index.md
Labels: update

#3281 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: update

#3282 update(SVG): web/svg
  files/uk/web/svg/index.md
Labels: translation, update, size/XS

#3285 update(HTML): web/html/attributes
  files/uk/web/html/attributes/index.md
Labels: update

#3286 update(CSS): web/css/id_selectors
  files/uk/web/css/id_selectors/index.md
Labels: translation, update, size/S

#3288 update(CSS): web/css/type_selectors
  files/uk/web/css/type_selectors/index.md
Labels: update

#3289 update(HTML): web/html/element/input/email
  files/uk/web/html/element/input/email/index.md
Labels: translation, update, size/M

#3292 update(HTML): web/html/attributes/required
  files/uk/web/html/attributes/required/index.md
Labels: translation, update, size/S

#3291 update(HTML): web/html/attributes/rel
  files/uk/web/html/attributes/rel/index.md
Labels: translation, update, size/S

#3294 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: translation, update, size/M

#3299 update(CSS): web/css/-moz-force-broken-image-icon
  files/uk/web/css/-moz-force-broken-image-icon/index.md
Labels: translation, update, size/S

#3300 update(CSS): web/css/_colon_invalid
  files/uk/web/css/_colon_invalid/index.md
Labels: translation, update, size/S

#3301 update(CSS): web/css/_colon_optional
  files/uk/web/css/_colon_optional/index.md
Labels: translation, update, size/S

#3303 update(CSS): web/css/_colon_required
  files/uk/web/css/_colon_required/index.md
Labels: translation, update, size/S

#3304 update(CSS): web/css/_colon_user-invalid
  files/uk/web/css/_colon_user-invalid/index.md
Labels: translation, update, size/S

#3305 update(CSS): web/css/_colon_valid
  files/uk/web/css/_colon_valid/index.md
Labels: translation, update, size/S

#3293 update(HTML): web/html/attributes/required
  files/uk/web/html/attributes/required/index.md
Labels: translation, update, size/S, Criticality: zero

#3276 update(HTML): web/html
  files/uk/web/html/index.md
Labels: translation, update, size/S, Criticality: mild

#3280 update(CSS): web/css/flex
  files/uk/web/css/flex/index.md
Labels: translation, update, size/M, Criticality: mild

#3309 translation(JS): web/javascript/reference/global_objects/object/is
  files/uk/web/javascript/reference/global_objects/object/is/index.md
Labels: translation, size/M, Criticality: mild

#3308 translation(HTML): web/html/element/picture
  files/uk/web/html/element/picture/index.md
Labels: translation, size/M, Criticality: mild

#3311 translation(CSS): web/css/_doublecolon_before
  files/uk/web/css/_doublecolon_before/index.md
  uk_spelling_additions.txt
Labels: translation, size/M

#3302 update(CSS): web/css/_colon_read-only
  files/uk/web/css/_colon_read-only/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/S, Criticality: zero

#3306 update(CSS): web/css/at-rule
  files/uk/web/css/at-rule/index.md
Labels: translation, update, size/M, Criticality: zero

#3297 translation(CSS): web/css/counters
  files/uk/web/css/counters/index.md
Labels: translation, size/M, Criticality: mild

#3287 update(CSS): web/css/containing_block
  files/uk/web/css/containing_block/index.md
Labels: translation, update, size/S, Criticality: low

#3290 update(HTML): web/html/global_attributes/class
  files/uk/web/html/global_attributes/class/index.md
Labels: translation, update, size/S, Criticality: zero

#2732 translation(JS): web/javascript/reference/functions/arguments
  files/uk/web/javascript/reference/functions/arguments/index.md
  uk_spelling_additions.txt
Labels: translation, size/M, Criticality: mild

#3284 update(CSS): web/css/height
  files/uk/web/css/height/index.md
Labels: translation, update, size/S, Criticality: low

#3283 update(CSS): web/css/width
  files/uk/web/css/width/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/S, Criticality: low

#1766 translation(HTML): web/html/constraint_validation
  files/uk/web/html/constraint_validation/index.md
Labels: translation, size/L, Criticality: mild

#3313 translation(HTML): web/html/element/tr
  files/uk/web/html/element/tr/index.md
Labels: translation, size/L, Criticality: zero

#3319 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update, size/M

#3326 update(CSS): web/css/transform-function
  files/uk/web/css/transform-function/index.md
Labels: update

#3327 update(HTML): web/html/element/textarea
  files/uk/web/html/element/textarea/index.md
Labels: translation, update, size/S

#3328 update(HTML): web/html/element/input/text
  files/uk/web/html/element/input/text/index.md
Labels: translation, update, size/M

#3329 update(HTML): web/html/element/heading_elements
  files/uk/web/html/element/heading_elements/index.md
Labels: translation, update, size/XS

#3331 update(HTML): web/html/element/input/time
  files/uk/web/html/element/input/time/index.md
Labels: translation, update, size/XS

#3335 update(JS): web/javascript/reference/global_objects/array/at
  files/uk/web/javascript/reference/global_objects/array/at/index.md
Labels: translation, update, size/S

#3336 update(Glossary): glossary/base64
  files/uk/glossary/base64/index.md
Labels: translation, update, size/S

#3337 update(HTML): web/html/element/input/tel
  files/uk/web/html/element/input/tel/index.md
Labels: translation, update, size/M

#3339 update(HTML): web/html/attributes/rel
  files/uk/web/html/attributes/rel/index.md
Labels: translation, update, size/XS

#3341 update(HTML): web/html/attributes/required
  files/uk/web/html/attributes/required/index.md
Labels: update

#3322 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: translation, update, size/S

#3342 update(JS): web/javascript/reference/global_objects/nan
  files/uk/web/javascript/reference/global_objects/nan/index.md
Labels: translation, update, size/S

#3343 update(JS): web/javascript/reference/lexical_grammar
  files/uk/web/javascript/reference/lexical_grammar/index.md
Labels: translation, update, size/M

#3340 update(HTML): web/html/element/input/url
  files/uk/web/html/element/input/url/index.md
Labels: translation, update, size/M

#3344 translation(JS): web/javascript/reference/operators/logical_or
  files/uk/web/javascript/reference/operators/logical_or/index.md
  uk_spelling_additions.txt
Labels: translation, size/M, Criticality: low

#3333 update(JS): web/javascript/reference/statements/let
  files/uk/web/javascript/reference/statements/let/index.md
Labels: translation, update, size/S, Criticality: low

#3332 update(JS): web/javascript/reference/functions
  files/uk/web/javascript/reference/functions/index.md
Labels: translation, update, size/S, Criticality: zero

#3330 update(HTML): web/html/global_attributes
  files/uk/web/html/global_attributes/index.md
Labels: translation, update, size/S, Criticality: low

#3320 update(CSS): web/css/flex
  files/uk/web/css/flex/index.md
Labels: translation, update, size/S, Criticality: mild

#3318 update(JS): web/javascript/reference/statements/import
  files/uk/web/javascript/reference/statements/import/index.md
Labels: translation, update, size/S, Criticality: low

#3317 translation(Glossary): glossary/accessibility
  files/uk/glossary/accessibility/index.md
Labels: translation, size/S, Criticality: mild

#3324 update(JS): web/javascript/closures
  files/uk/web/javascript/closures/index.md
Labels: translation, update, size/M, Criticality: mild

#3325 update(CSS): web/css/flex-basis
  files/uk/web/css/flex-basis/index.md
Labels: translation, update, size/M, Criticality: low

#3323 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: translation, update, size/S, Criticality: mild

#3334 update(JS): web/javascript/reference/iteration_protocols
  files/uk/web/javascript/reference/iteration_protocols/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/M, Criticality: low

#2975 update(CSS): web/css/css_box_model
  files/uk/web/css/css_box_model/boxmodel.png
  files/uk/web/css/css_box_model/index.md
Labels: translation, update, size/M, Criticality: zero

#3316 translation(Glossary): glossary/scroll_container
  files/uk/glossary/scroll_container/index.md
  uk_spelling_additions.txt
Labels: translation, size/S, Criticality: mild

#3349 update(CSS): web/css/font-size
  files/uk/web/css/font-size/index.md
Labels: translation, update, size/S

#3350 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: translation, update, size/M

#3351 update(JS): web/javascript/reference/global_objects/intl
  files/uk/web/javascript/reference/global_objects/intl/index.md
Labels: update
