Repository webdoky/content, pull requests merged in 2024-10, with the labels that each got.

#3376 translation(CSS): web/css/transition
  files/uk/web/css/transition/index.md
Labels: translation, size/M, Criticality: low

#3312 translation(CSS): web/css/overflow-x
  files/uk/web/css/overflow-x/index.md
Labels: translation, size/M, Criticality: mild

#3352 translation(Glossary): glossary/control_flow
  files/uk/glossary/control_flow/index.md
  uk_spelling_additions.txt
Labels: translation, size/M, Criticality: mild

#3346 translation(Glossary): glossary/accessible_description
  files/uk/glossary/accessible_description/index.md
Labels: translation, size/M, Criticality: mild

#3345 translation(Glossary): glossary/accessible_name
  en_spelling_additions.txt
  files/uk/glossary/accessible_name/index.md
Labels: translation, size/M, Criticality: mild

#3381 translation(JS): web/javascript/reference/global_objects/array/flatmap
  files/uk/web/javascript/reference/global_objects/array/flatmap/index.md
Labels: translation, size/M, Criticality: mild

#3384 update(JS): web/javascript/reference/global_objects/array
  files/uk/web/javascript/reference/global_objects/array/index.md
Labels: translation, update, size/S

#3386 update(HTML): web/html/element
  files/uk/web/html/element/index.md
Labels: translation, update, size/XS

#3394 update(CSS): web/css/using_css_custom_properties
  files/uk/web/css/using_css_custom_properties/index.md
Labels: update

#3395 update(CSS): web/css/background-image
  files/uk/web/css/background-image/cat-front.png
  files/uk/web/css/background-image/index.md
  files/uk/web/css/background-image/star-transparent.gif
Labels: translation, update, size/XS

#3388 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, update, size/S

#3390 update(JS): web/javascript/reference/global_objects/json/stringify
  files/uk/web/javascript/reference/global_objects/json/stringify/index.md
Labels: translation, update, size/S

#3396 update(JS): web/javascript/reference/operators/spread_syntax
  files/uk/web/javascript/reference/operators/spread_syntax/index.md
Labels: translation, update, size/S

#3397 update(CSS): web/css/cursor
  files/uk/web/css/cursor/index.md
Labels: translation, update, size/S

#3398 update(HTML): web/html/element/input/checkbox
  files/uk/web/html/element/input/checkbox/index.md
Labels: translation, update, size/M

#3399 update(HTML): web/html/element/input/file
  files/uk/web/html/element/input/file/index.md
Labels: translation, update, size/S

#3400 update(JS): web/javascript/reference/global_objects/object/assign
  files/uk/web/javascript/reference/global_objects/object/assign/index.md
Labels: translation, update, size/S

#3401 update(CSS): web/css/font-weight
  files/uk/web/css/font-weight/index.md
Labels: translation, update, size/S

#3402 update(CSS): web/css/grid-template-columns
  files/uk/web/css/grid-template-columns/index.md
Labels: translation, update, size/S

#3403 update(CSS): web/css/vertical-align
  files/uk/web/css/vertical-align/index.md
Labels: translation, update, size/XS

#3404 update(HTML): web/html/element/a
  files/uk/web/html/element/a/index.md
Labels: translation, update, size/XS

#3405 update(HTML): web/html/element/select
  files/uk/web/html/element/select/index.md
Labels: translation, update, size/S

#3406 update(HTML): web/html/element/button
  files/uk/web/html/element/button/index.md
Labels: translation, update, size/S

#3407 update(JS): web/javascript/reference/operators/nullish_coalescing
  files/uk/web/javascript/reference/operators/nullish_coalescing/index.md
Labels: translation, update, size/XS

#3408 update(CSS): web/css/background-position
  files/uk/web/css/background-position/cat-front.png
  files/uk/web/css/background-position/index.md
  files/uk/web/css/background-position/star-transparent.gif
Labels: translation, update, size/XS

#3409 update(CSS): web/css/transform
  files/uk/web/css/transform/index.md
Labels: translation, update, size/XS

#3410 update(CSS): web/css/text-overflow
  files/uk/web/css/text-overflow/index.md
Labels: translation, update, size/S

#3411 update(CSS): web/css/background-color
  files/uk/web/css/background-color/index.md
Labels: translation, update, size/S

#3413 update(CSS): web/css/background
  files/uk/web/css/background/index.md
  files/uk/web/css/background/star-solid.gif
Labels: translation, update, size/XS

#3416 update(CSS): web/css/flex-direction
  files/uk/web/css/flex-direction/index.md
Labels: translation, update, size/S

#3419 update(HTML): web/html/element/input/number
  files/uk/web/html/element/input/number/index.md
Labels: translation, update, size/S

#3420 update(HTML): web/html/element/div
  files/uk/web/html/element/div/index.md
Labels: translation, update, size/S

#3424 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: translation, update, size/S

#3425 update(JS): web/javascript/reference/global_objects/array/flat
  files/uk/web/javascript/reference/global_objects/array/flat/index.md
Labels: translation, update, size/S

#3426 update(JS): web/javascript/guide/using_promises
  files/uk/web/javascript/guide/using_promises/index.md
Labels: translation, update, size/S

#3427 update(JS): web/javascript/reference/operators/await
  files/uk/web/javascript/reference/operators/await/index.md
Labels: translation, update, size/S

#3428 update(CSS): web/css/padding
  files/uk/web/css/padding/index.md
Labels: translation, update, size/S

#3429 update(CSS): web/css/text-align
  files/uk/web/css/text-align/index.md
Labels: update

#3432 update(CSS): web/css/reference
  files/uk/web/css/reference/index.md
Labels: translation, update, size/S

#3434 update(CSS): web/css/height
  files/uk/web/css/height/index.md
Labels: translation, update, size/XS

#3433 update(CSS): web/css/width
  files/uk/web/css/width/index.md
Labels: translation, update, size/S

#3415 update(CSS): web/css/backdrop-filter
  files/uk/web/css/backdrop-filter/index.md
Labels: update

#3435 update(HTML): web/html/element/label
  files/uk/web/html/element/label/index.md
Labels: translation, update, size/S

#3437 update(HTML): web/html/element/i
  files/uk/web/html/element/i/index.md
Labels: translation, update, size/S

#3438 update(HTML): web/html/element/input/text
  files/uk/web/html/element/input/text/index.md
Labels: translation, update, size/S

#3439 update(HTML): web/html/element/input/datetime-local
  files/uk/web/html/element/input/datetime-local/index.md
Labels: translation, update, size/S

#3441 update(HTML): web/html/element/picture
  files/uk/web/html/element/picture/index.md
Labels: translation, update, size/S

#3442 update(HTML): web/html/element/tr
  files/uk/web/html/element/tr/index.md
Labels: translation, update, size/S

#3444 update(HTML): web/html/element/input/submit
  files/uk/web/html/element/input/submit/index.md
Labels: translation, update, size/S

#3445 update(HTML): web/html/element/span
  files/uk/web/html/element/span/index.md
Labels: translation, update, size/S

#3446 update(HTML): web/html/element/input/time
  files/uk/web/html/element/input/time/index.md
Labels: translation, update, size/S

#3447 update(HTML): web/html/attributes/autocomplete
  files/uk/web/html/attributes/autocomplete/index.md
Labels: translation, update, size/S

#3448 update(HTML): web/html/attributes
  files/uk/web/html/attributes/index.md
Labels: translation, update, size/S

#3449 update(HTML): web/html/element/input/button
  files/uk/web/html/element/input/button/index.md
Labels: translation, update, size/S

#3450 update(JS): web/javascript/reference/global_objects/error
  files/uk/web/javascript/reference/global_objects/error/index.md
Labels: translation, update, size/S

#3451 update(JS): web/javascript/reference/global_objects/json
  files/uk/web/javascript/reference/global_objects/json/index.md
Labels: update

#3452 update(JS): web/javascript/reference/iteration_protocols
  files/uk/web/javascript/reference/iteration_protocols/index.md
Labels: update

#3387 update(HTML): web/html/element/input
  files/uk/web/html/element/input/index.md
Labels: translation, update, size/M

#3391 update(CSS): web/css/position
  files/uk/web/css/position/index.md
Labels: translation, update, size/M

#3412 update(CSS): web/css/calc
  files/uk/web/css/calc/index.md
Labels: translation, update, size/S

#3421 update(HTML): web/html/element/script
  files/uk/web/html/element/script/index.md
Labels: translation, update, size/S

#3422 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: translation, update, size/S

#3423 update(JS): web/javascript/reference/global_objects/array/from
  files/uk/web/javascript/reference/global_objects/array/from/index.md
Labels: translation, update, size/S

#3430 update(CSS): web/css/margin
  files/uk/web/css/margin/index.md
Labels: translation, update, size/XS

#3453 update(CSS): web/css/font
  files/uk/web/css/font/index.md
Labels: translation, update, size/S

#3454 update(CSS): web/css/class_selectors
  files/uk/web/css/class_selectors/index.md
Labels: translation, update, size/XS

#3455 update(CSS): web/css/--_star_
  files/uk/web/css/--_star_/index.md
Labels: translation, update, size/S

#3456 update(CSS): web/css/value_definition_syntax
  files/uk/web/css/value_definition_syntax/index.md
Labels: translation, update, size/S

#3457 update(HTML): web/html/element/input/email
  files/uk/web/html/element/input/email/index.md
Labels: translation, update, size/S

#3458 update(HTML): web/html/element/datalist
  files/uk/web/html/element/datalist/index.md
Labels: translation, update, size/S

#3459 update(HTML): web/html/element/input/search
  files/uk/web/html/element/input/search/index.md
Labels: translation, update, size/S

#3460 update(HTML): web/html/element/fieldset
  files/uk/web/html/element/fieldset/index.md
Labels: translation, update, size/S

#3461 update(HTML): web/html/element/input/hidden
  files/uk/web/html/element/input/hidden/index.md
Labels: translation, update, size/S

#3462 update(HTML): web/html/element/input/month
  files/uk/web/html/element/input/month/index.md
Labels: translation, update, size/S

#3463 update(HTML): web/html/attributes/rel
  files/uk/web/html/attributes/rel/index.md
Labels: translation, update, size/S

#3464 update(HTML): web/html/element/input/reset
  files/uk/web/html/element/input/reset/index.md
Labels: translation, update, size/S

#3465 update(HTML): web/html/element/input/url
  files/uk/web/html/element/input/url/index.md
Labels: translation, update, size/S

#3466 update(HTML): web/html/element/source
  files/uk/web/html/element/source/index.md
Labels: translation, update, size/S

#3467 update(Glossary): glossary/callback_function
  files/uk/glossary/callback_function/index.md
Labels: translation, update, size/S

#3468 update(Glossary): glossary/deep_copy
  files/uk/glossary/deep_copy/index.md
Labels: translation, update, size/S

#3469 update(CSS): web/css/_colon_indeterminate
  files/uk/web/css/_colon_indeterminate/index.md
Labels: translation, update, size/S

#3470 update(CSS): web/css/_colon_placeholder-shown
  files/uk/web/css/_colon_placeholder-shown/index.md
Labels: update

#3471 update(CSS): web/css/_colon_read-only
  files/uk/web/css/_colon_read-only/index.md
Labels: translation, update, size/XS

#3472 update(CSS): web/css/_colon_read-write
  files/uk/web/css/_colon_read-write/index.md
Labels: translation, update, size/S

#3473 update(CSS): web/css/_doublecolon_placeholder
  files/uk/web/css/_doublecolon_placeholder/index.md
Labels: translation, update, size/S

#3475 update(CSS): web/css/at-rule
  files/uk/web/css/at-rule/index.md
Labels: translation, update, size/S

#3476 update(CSS): web/css/caret-color
  files/uk/web/css/caret-color/index.md
Labels: translation, update, size/S

#3477 update(CSS): web/css/color
  files/uk/web/css/color/index.md
Labels: update

#3478 update(CSS): web/css/computed_value
  files/uk/web/css/computed_value/index.md
Labels: translation, update, size/S

#3479 update(CSS): web/css/counters
  files/uk/web/css/counters/index.md
Labels: update

#3480 update(CSS): web/css/initial_value
  files/uk/web/css/initial_value/index.md
Labels: translation, update, size/XS

#3484 update(CSS): web/css/used_value
  files/uk/web/css/used_value/index.md
Labels: translation, update, size/S

#3486 update(HTML): web/html/attributes/min
  files/uk/web/html/attributes/min/index.md
Labels: translation, update, size/S

#3487 update(HTML): web/html/attributes/max
  files/uk/web/html/attributes/max/index.md
Labels: translation, update, size/S

#3488 update(HTML): web/html/attributes/step
  files/uk/web/html/attributes/step/index.md
Labels: translation, update, size/S

#3489 update(HTML): web/html/element/area
  files/uk/web/html/element/area/index.md
Labels: translation, update, size/S

#3492 update(HTML): web/html/element/optgroup
  files/uk/web/html/element/optgroup/index.md
Labels: translation, update, size/XS

#3493 update(HTML): web/html/element/input/week
  files/uk/web/html/element/input/week/index.md
Labels: translation, update, size/M

#3495 update(JS): web/javascript/reference/functions/arrow_functions
  files/uk/web/javascript/reference/functions/arrow_functions/index.md
Labels: translation, update, size/S

#3496 update(JS): web/javascript/reference/operators/property_accessors
  files/uk/web/javascript/reference/operators/property_accessors/index.md
Labels: translation, update, size/S

#3497 update(JS): web/javascript/reference/global_objects/math/acos
  files/uk/web/javascript/reference/global_objects/math/acos/index.md
Labels: translation, update, size/XS

#3485 update(CSS): web/css/image
  files/uk/web/css/image/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/S

#3482 update(CSS): web/css/replaced_element
  files/uk/web/css/replaced_element/index.md
Labels: translation, update, size/S

#3474 update(CSS): web/css/@media
  files/uk/web/css/@media/index.md
Labels: translation, update, size/S

#3490 update(HTML): web/html/element/audio
  files/uk/web/html/element/audio/index.md
Labels: translation, update, size/S

#3481 update(CSS): web/css/object-fit
  files/uk/web/css/object-fit/index.md
Labels: translation, update, size/S

#3392 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: translation, update, size/S

#3414 update(CSS): web/css/text-transform
  files/uk/web/css/text-transform/index.md
Labels: translation, update, size/S

#3443 update(HTML): web/html/element/link
  files/uk/web/html/element/link/index.md
Labels: translation, update, size/S

#3440 update(HTML): web/html/element/heading_elements
  files/uk/web/html/element/heading_elements/index.md
Labels: translation, update, size/S

#3436 update(HTML): web/html/element/textarea
  files/uk/web/html/element/textarea/index.md
Labels: translation, update, size/S

#3418 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: translation, update, size/M

#3499 update(JS): web/javascript/inheritance_and_the_prototype_chain
  files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
Labels: update

#3500 update(JS): web/javascript/guide/functions
  files/uk/web/javascript/guide/functions/index.md
Labels: update

#3501 update(JS): web/javascript/guide/loops_and_iteration
  files/uk/web/javascript/guide/loops_and_iteration/index.md
Labels: translation, update, size/S

#3502 update(JS): web/javascript/guide/modules
  files/uk/web/javascript/guide/modules/index.md
Labels: translation, update, size/S

#3503 update(JS): web/javascript/reference/operators/destructuring_assignment
  files/uk/web/javascript/reference/operators/destructuring_assignment/index.md
Labels: translation, update, size/S

#3504 update(JS): web/javascript/reference/operators/function
  files/uk/web/javascript/reference/operators/function/index.md
Labels: update

#3505 update(JS): web/javascript/reference/operators/optional_chaining
  files/uk/web/javascript/reference/operators/optional_chaining/index.md
Labels: translation, update, size/S

#3506 update(JS): web/javascript/reference/statements/try...catch
  files/uk/web/javascript/reference/statements/try...catch/index.md
Labels: translation, update, size/XS

#3507 update(JS): web/javascript/reference/global_objects/array/some
  files/uk/web/javascript/reference/global_objects/array/some/index.md
Labels: translation, update, size/S

#3508 update(JS): web/javascript/reference/global_objects/bigint
  files/uk/web/javascript/reference/global_objects/bigint/index.md
Labels: update

#3509 update(JS): web/javascript/reference/global_objects/map
  files/uk/web/javascript/reference/global_objects/map/index.md
Labels: update

#3510 update(JS): web/javascript/reference/global_objects/math/acosh
  files/uk/web/javascript/reference/global_objects/math/acosh/index.md
Labels: translation, update, size/XS

#3511 update(JS): web/javascript/reference/global_objects/math/asin
  files/uk/web/javascript/reference/global_objects/math/asin/index.md
Labels: translation, update, size/XS

#3512 update(JS): web/javascript/reference/global_objects/math/asinh
  files/uk/web/javascript/reference/global_objects/math/asinh/index.md
Labels: translation, update, size/XS

#3513 update(JS): web/javascript/reference/global_objects/math/atan
  files/uk/web/javascript/reference/global_objects/math/atan/index.md
Labels: translation, update, size/XS

#3514 update(JS): web/javascript/reference/global_objects/math/atanh
  files/uk/web/javascript/reference/global_objects/math/atanh/index.md
Labels: translation, update, size/XS

#3515 update(JS): web/javascript/reference/global_objects/math/cbrt
  files/uk/web/javascript/reference/global_objects/math/cbrt/index.md
Labels: translation, update, size/XS

#3516 update(JS): web/javascript/reference/global_objects/math/clz32
  files/uk/web/javascript/reference/global_objects/math/clz32/index.md
Labels: translation, update, size/XS

#3517 update(JS): web/javascript/reference/global_objects/math/cosh
  files/uk/web/javascript/reference/global_objects/math/cosh/index.md
Labels: update

#3518 update(JS): web/javascript/reference/global_objects/math/exp
  files/uk/web/javascript/reference/global_objects/math/exp/index.md
Labels: update

#3519 update(JS): web/javascript/reference/global_objects/math/e
  files/uk/web/javascript/reference/global_objects/math/e/index.md
Labels: update

#3383 translation(CSS): web/css/pointer-events
  files/uk/web/css/pointer-events/index.md
Labels: translation, size/M, Criticality: mild
