Repository webdoky/content, pull requests merged in 2024-05, with the labels that each got.

#2980 translation(HTML): web/html/element/li
  files/uk/web/html/element/li/index.md
Labels: translation, size/M, Criticality: mild

#2983 update(HTML): web/html/element/video
  files/uk/web/html/element/video/index.md
Labels: translation, update, size/S

#2984 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
  uk_spelling_additions.txt
Labels: translation, update, size/S

#2985 update(JS): web/javascript/reference/statements
  files/uk/web/javascript/reference/statements/index.md
Labels: translation, update, size/S

#2986 update(Glossary): glossary
  files/uk/glossary/index.md
Labels: update, size/XXS

#2987 update(CSS): web/css/transform-function/translate
  files/uk/web/css/transform-function/translate/index.md
Labels: update

#2988 update(JS): web/javascript/reference/global_objects/array/push
  files/uk/web/javascript/reference/global_objects/array/push/index.md
Labels: translation, update, size/XS

#2990 update(JS): web/javascript/reference/global_objects/math/random
  files/uk/web/javascript/reference/global_objects/math/random/index.md
Labels: translation, update, size/S

#2993 update(CSS): web/css/align-items
  files/uk/web/css/align-items/index.md
Labels: translation, update, size/S

#2994 update(CSS): web/css/object-fit
  files/uk/web/css/object-fit/index.md
Labels: translation, update, size/S

#2995 update(HTML): web/html/element/img
  files/uk/web/html/element/img/index.md
Labels: translation, update, size/S

#2998 update(SVG): web/svg
  files/uk/web/svg/index.md
Labels: update

#2999 update(CSS): web/css/@media
  files/uk/web/css/@media/index.md
Labels: translation, update, size/XS

#3000 update(HTML): web/html/element/audio
  files/uk/web/html/element/audio/index.md
Labels: translation, update, size/S

#3001 update(HTML): web/html/attributes
  files/uk/web/html/attributes/index.md
Labels: update, size/XXS

#3003 update(HTML): web/html/element/input/search
  files/uk/web/html/element/input/search/index.md
Labels: translation, update, size/S

#3004 update(HTML): web/html/element/input/image
  files/uk/web/html/element/input/image/index.md
Labels: translation, update, size/S

#3006 update(SVG): web/svg/attribute
  files/uk/web/svg/attribute/index.md
Labels: update, size/XXS

#3007 update(Glossary): glossary/preflight_request
  files/uk/glossary/preflight_request/index.md
Labels: update

#3008 update(Glossary): glossary/deep_copy
  files/uk/glossary/deep_copy/index.md
Labels: translation, update, size/XS

#3010 translation(JS): web/javascript/reference/global_objects/array/at
  files/uk/web/javascript/reference/global_objects/array/at/index.md
Labels: translation, size/M, Criticality: mild
