Repository webdoky/content, pull requests merged in 2025-01, with the labels that each got.

#3761 translation(CSS): web/css/_colon_has-slotted
  files/uk/web/css/_colon_has-slotted/index.md
Labels: translation, size/S, Criticality: low

#3753 translation(CSS): web/css/layout_cookbook
  files/uk/web/css/layout_cookbook/index.md
  uk_spelling_additions.txt
Labels: translation, size/M, Criticality: mild

#3764 translation(JS): web/javascript/reference/global_objects/isnan
  files/uk/web/javascript/reference/global_objects/isnan/index.md
Labels: translation, size/M

#3767 translation(CSS): web/css/scroll-padding
  files/uk/web/css/scroll-padding/index.md
Labels: translation, size/M

#3768 translation(HTML): web/html/global_attributes/id
  files/uk/web/html/global_attributes/id/index.md
Labels: translation, size/M

#3770 translation(CSS): web/css/scroll-padding-block
  files/uk/web/css/scroll-padding-block/index.md
Labels: translation, size/M

#3775 update(JS): web/javascript
  files/uk/web/javascript/index.md
Labels: translation, update, size/S

#3776 update(JS): web/javascript/reference
  files/uk/web/javascript/reference/index.md
Labels: update

#3778 update(JS): web/javascript/reference/global_objects/date
  files/uk/web/javascript/reference/global_objects/date/index.md
Labels: translation, update, size/S

#3779 update(JS): web/javascript/reference/global_objects/string
  files/uk/web/javascript/reference/global_objects/string/index.md
Labels: translation, update, size/XS
